### ISSUE TITLE
Build ASP.net core 3.0

### ISSUE THREAD

**Issue by JohnTraDolta** [jincod/dotnetcore-buildpack#101]
can not build target framework 3.0 
 
The project use is a new and clean ASP.net core project (MVC application) with target framework 3.0 and Identity (Individual user, stored on web app) 

Log from heroku:
```
-----> ASP.NET Core app detected
Installing dotnet
-----> Removing old cached .NET version
-----> Fetching .NET SDK
-----> Fetching .NET Runtime
publish /tmp/build_ef9f59db13d24fb845a3d280a19790c2/UnibarApi/UnibarApi.csproj
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
/app/tmp/cache/dotnet/2.2.105/sdk/sdk/2.2.105/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/tmp/build_ef9f59db13d24fb845a3d280a19790c2/UnibarApi/UnibarApi.csproj]
 !     Push rejected, failed to compile ASP.NET Core app.
 !     Push failed
```

**Comment by jincod** [comment]
Hi @JohnTraDolta,

According to the error you use sdk v2.2.105. Make sure that you use the latest buildpack version (3.0).

**Comment by JohnTraDolta** [comment]
sorry my bad :) 

how do i make sure i use the latest buildpack? 

i am new to heroku and buildpacks

**Comment by jincod** [comment]
You can specify version `https://github.com/jincod/dotnetcore-buildpack#v3.0.100`. Here the full command https://github.com/jincod/dotnetcore-buildpack#previous-releases

**Comment by JohnTraDolta** [comment]
Thanks buddy, it's works
