### ISSUE TITLE
I can't publish Asp.Net Core app

### ISSUE THREAD

**Issue by super1515** [jincod/dotnetcore-buildpack#102]
> The specified framework 'Microsoft.NETCore.App', version '2.0.9' was not found. remote: - The following frameworks were found: remote: 3.0.0 at [/app/tmp/cache/dotnet/3.0.100/sdk/shared/Microsoft.NETCore.App] My.csproj file:
.csproj file:

**Comment by jincod** [comment]
Hi @super1515,

Have you checked this issue https://github.com/jincod/dotnetcore-buildpack/issues/101?
