### ISSUE TITLE
Blazor WebAssembly build fail

### ISSUE THREAD

**Issue by besso-exceline** [jincod/dotnetcore-buildpack#107]
Can not deploy Blazor WebAssembly app from latest release, I think reason is the SDK version used by buildpack: 3.1.101, but my app uses 3.1.102

here is the error message

Fatal error in Mono IL Linker
Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly

**Comment by jincod** [comment]
Hi @besso-exceline,

What is your buildpack url? 

Also I've pushed tag `v3.1.102` and you can try to specify it explicitly

**Comment by besso-exceline** [comment]
Hi,

changed from https://buildpack-registry.s3.amazonaws.com/buildpacks/jincod/dotnetcore.tgz
to https://github.com/jincod/dotnetcore-buildpack
and it worked. Build works fine now.

But the application is crashing on start. Application runs only after first deployment, but it crashes when I push second time. I tried heroku config:set SBT_CLEAN=true  
but it did not help.

Application I am trying to get on Heroku is Visual Studio default template Blazor asp .net core hosted app.

**Comment by jincod** [comment]
Could you provide build and app logs?

**Comment by besso-exceline** [comment]
**Build log:**
C:\Users\Besso\source\net\BlazorApp1>git push heroku master
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 507 bytes | 507.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> ASP.NET Core app detected
remote: > Installing dotnet
remote: -----> Export dotnet to Path
remote: -----> Project File
remote: > /tmp/build_f335622a248621585c7242ac4ad88a5d/BlazorApp1/Client/BlazorApp1.Client.csproj
remote: -----> Project Name
remote: > BlazorApp1.Client
remote: > publish /tmp/build_f335622a248621585c7242ac4ad88a5d/BlazorApp1/Client/BlazorApp1.Client.csproj for Release
remote:
remote: Welcome to .NET Core 3.1!
remote: ---------------------
remote: SDK Version: 3.1.102
remote:
remote: ----------------
remote: Explore documentation: https://aka.ms/dotnet-docs
remote: Report issues and find source on GitHub: https://github.com/dotnet/core
remote: Find out what's new: https://aka.ms/dotnet-whats-new
remote: Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
remote: Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
remote: Write your first app: https://aka.ms/first-net-core-app
remote: --------------------------------------------------------------------------------------
remote: Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
remote: Copyright (C) Microsoft Corporation. All rights reserved.
remote:
remote:   Restore completed in 327.85 ms for /tmp/build_f335622a248621585c7242ac4ad88a5d/BlazorApp1/Shared/BlazorApp1.Shared.csproj.
remote:   Restore completed in 380.05 ms for /tmp/build_f335622a248621585c7242ac4ad88a5d/BlazorApp1/Client/BlazorApp1.Client.csproj.
remote:   BlazorApp1.Shared -> /tmp/build_f335622a248621585c7242ac4ad88a5d/BlazorApp1/Shared/bin/Release/netstandard2.1/BlazorApp1.Shared.dll
remote:   BlazorApp1.Client -> /tmp/build_f335622a248621585c7242ac4ad88a5d/BlazorApp1/Client/bin/Release/netstandard2.1/linux-x64/BlazorApp1.Client.dll
remote:   BlazorApp1.Client (Blazor output) -> /tmp/build_f335622a248621585c7242ac4ad88a5d/BlazorApp1/Client/bin/Release/netstandard2.1/linux-x64/wwwroot
remote:   BlazorApp1.Client -> /tmp/build_f335622a248621585c7242ac4ad88a5d/heroku_output/
remote:        Add web process to Procfile
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 40.4M
remote: -----> Launching...
remote:        Released v5
remote:        https://blazorwa.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/blazorwa.git
   5b6ebee..7b427fb  master -> master




**App log:**
2020-03-13T08:56:54.000000+00:00 app[api]: Build started by user 
2020-03-13T08:57:22.775317+00:00 app[api]: Deploy 7b427fb4 by user 
2020-03-13T08:57:22.775317+00:00 app[api]: Release v5 created by user 
2020-03-13T08:57:24.428392+00:00 heroku[web.1]: State changed from crashed to starting
2020-03-13T08:57:26.483225+00:00 heroku[web.1]: Starting process with command `cd /app/heroku_output && ./BlazorApp1.Client`
2020-03-13T08:57:27.719669+00:00 heroku[web.1]: State changed from starting to crashed
2020-03-13T08:57:27.797605+00:00 heroku[web.1]: State changed from crashed to starting
2020-03-13T08:57:27.702683+00:00 heroku[web.1]: Process exited with status 127
2020-03-13T08:57:27.669855+00:00 app[web.1]: bash: ./BlazorApp1.Client: No such file or directory
2020-03-13T08:57:30.152764+00:00 heroku[web.1]: Starting process with command `cd /app/heroku_output && ./BlazorApp1.Client`
2020-03-13T08:57:33.285779+00:00 heroku[web.1]: State changed from starting to crashed
2020-03-13T08:57:33.272521+00:00 heroku[web.1]: Process exited with status 127
2020-03-13T08:57:33.137605+00:00 app[web.1]: bash: ./BlazorApp1.Client: No such file or directory
2020-03-13T08:57:58.000000+00:00 app[api]: Build succeeded
2020-03-13T08:58:45.575221+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=blazorwa.herokuapp.com request_id=fbadfb89-5d64-4e69-88b5-c8d867ea937a fwd="" dyno= connect= service= status=503 bytes= protocol=https

**Comment by jincod** [comment]
Have you checked https://github.com/jincod/dotnetcore-buildpack/issues/75?

**Comment by besso-exceline** [comment]
OK, I see
I specified the PROJECT_FILE (with full path like this: BlazorApp1/Server/BlazorApp1.Server.csproj) as Heroku config var and it worked fine.

Thank you very much!
