### ISSUE TITLE
How can I deploy an app with an external reference?

### ISSUE THREAD

**Issue by Dakkers** [jincod/dotnetcore-buildpack#108]
This might be a general C# question but I'm pretty new to this whole thing. I have an API that has an Assembly Reference to another project on my computer. It's in a different directory. When I deploy, it says I'm missing the reference. I'm not sure how to compile my app such that the DLL is included with it. (Alternatively, if I could add a `git clone` to the buildpack somehow and compile it at deploy-time, that would be fine.)

**Comment by jincod** [comment]
Hi @Dakkers,

Try to use git submodules. https://devcenter.heroku.com/articles/git-submodules and https://github.com/SectorLabs/heroku-buildpack-git-submodule might be helpful

**Comment by Dakkers** [comment]
that ended up working! thank you very much
