### ISSUE TITLE
How to use Procfile?

### ISSUE THREAD

**Issue by ILAgent** [jincod/dotnetcore-buildpack#111]
Hi!
I've created Procfile with
`worker: cd $HOME/heroku_output && ./TI.Service`
but heroku tries to run
`worker: cd $HOME/heroku_output && ./TI.Serviceweb: cd $HOME/heroku_output && ./TI.Service`
Looks like a concatenation of my Procfile and something default.
How to fix?

**Comment by nortages** [comment]
I currently have the same issue
`worker cd $HOME/heroku_output && ./SegaTwitchBotweb: cd $HOME/heroku_output && ./SegaTwitchBot`

**Comment by jincod** [comment]
@nortages clear the Heroku cache (https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache) or specify the latest buildpack version 

```
heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack#af1f5e0
```

**Comment by nortages** [comment]
@jincod Cleaning Heroku cache helped. Thanks!
