### ISSUE TITLE
Error when deploying 

### ISSUE THREAD

**Issue by sydneyfunnelAIO** [jincod/dotnetcore-buildpack#112]
Hello,
I m trying deploy my first application. but when deploying there s a error .
![image](https://user-images.githubusercontent.com/51324523/80895538-c432f380-8cee-11ea-808b-fa46bd12b0eb.png)
and this is my files.
![image](https://user-images.githubusercontent.com/51324523/80895546-d57c0000-8cee-11ea-9167-5e13f82ab3d1.png)
btw I m trying deploy a console application(.net core 3.1)

**Comment by jincod** [comment]
Hi @sydneyfunnelAIO 

Is it built locally? Is `dotnet publish` worked locally?

Could you share your `csproj` file?

**Comment by sydneyfunnelAIO** [comment]
> Hi @sydneyfunnelAIO
> 
> Is it built locally? Is `dotnet publish` worked locally?
> 
> Could you share your `csproj` file?

this is my csproj -> 
![image](https://user-images.githubusercontent.com/51324523/80917909-8e335500-8d6a-11ea-9594-0599d630080f.png)

and also there my codes: 

`using System;
using TwitchLib.Client;
using TwitchLib.Client.Enums;
using TwitchLib.Client.Events;
using TwitchLib.Client.Extensions;
using TwitchLib.Client.Models;
using TwitchLib;
using TwitchLib.Communication.Models;
using TwitchLib.Communication.Clients;
using System.IO;
using System.Runtime.InteropServices;
using System.Diagnostics;
using System.Reflection;
using System.Security;

using System.Data;

using System.Data.OleDb;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using System.Timers;
using System.Threading;

namespace sydneybot

{
    class Program
    {
        static int SW_HIDE = 0;
        static int SW_SHOW = 5;
        static void Main(string[] args)

        {
          //  IntPtr mywindow = GetConsoleWindow();
           // ShowWindow(mywindow, SW_HIDE);
            Bot bot = new Bot();

            Console.ReadLine();
        }
        //[DllImport("user32.dll")]
        //static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
       // [DllImport("kernel32.dll")]
     //   static extern IntPtr GetConsoleWindow();



    }

    class Bot
    {
        TwitchClient client;

        public Bot()
        {


            string[] config = File.ReadAllLines(@"./config.txt", Encoding.UTF8);




            ConnectionCredentials credentials = new ConnectionCredentials(config[0], config[1]);
                var clientOptions = new ClientOptions
                {
                    MessagesAllowedInPeriod = 750,
                    ThrottlingPeriod = TimeSpan.FromSeconds(30)
                };
                WebSocketClient customClient = new WebSocketClient(clientOptions);
                client = new TwitchClient(customClient);
                client.Initialize(credentials, config[2]);

                client.OnLog += Client_OnLog;
                client.OnJoinedChannel += Client_OnJoinedChannel;
                client.OnMessageReceived += Client_OnMessageReceived;
                client.OnNewSubscriber += Client_OnNewSubscriber;
                client.OnConnected += Client_OnConnected;
               

                client.Connect();

            System.Timers.Timer atimer = new System.Timers.Timer();
            atimer.Elapsed += new ElapsedEventHandler(OnTimedEvent);
            atimer.Interval = 50000;
            atimer.Enabled = true;

        }
      
            
            

        
        private  void OnTimedEvent(Object source, ElapsedEventArgs e)
        {
            client.SendMessage("sydneyfunnelaio", "SydneyfunnelAIO tarafından üretildi! -> iletisim : sydneyfunnelallinone@gmail.com");
            Thread.Sleep(30000);
            client.SendMessage("sydneyfunnelaio", "Abone olarak bize Destekte bulunabilir Ayrıca asagidaki linklerden bagista bulunabilirsiniz!");
        }



        private void Client_OnLog(object sender, OnLogArgs e)
        {
            Console.WriteLine($"{e.DateTime.ToString()}: {e.BotUsername} - {e.Data}");
        }

        private void Client_OnConnected(object sender, OnConnectedArgs e)
        {
            Console.WriteLine($"Connected to {e.AutoJoinChannel}");
        }
        private void Client_OnChannelStateChanged(object sender, OnChannelStateChangedArgs e)
        {
            Console.WriteLine($"Connected to {e.ChannelState}");
        }
        private void Client_OnJoinedChannel(object sender, OnJoinedChannelArgs e)
        {
            Console.WriteLine("Selamlar!|| Sydney");
         
        }

        private void Client_OnMessageReceived(object sender, OnMessageReceivedArgs e)
        {
           

            string mesaj = e.ChatMessage.Message;
            char ayrac = ' ';
            string[] message = mesaj.Split(ayrac);

            if (e.ChatMessage.IsBroadcaster == true)
            {
                if (message[0].Equals("!add"))
                {
                   string resp = string.Join(" ", message[2..^0]);
                    
                    File.AppendAllText("command.txt",
                 message[1] + Environment.NewLine);
                    File.AppendAllText("response.txt",
                    resp+Environment.NewLine);
                    client.SendMessage(e.ChatMessage.Channel, message[1]+"başarıyla eklendi");
                }
            }

            List<string> list = File.ReadLines("./command.txt").ToList();
            List<string> list1 = File.ReadLines("./response.txt").ToList();
            string[] comm = File.ReadAllLines(@"./command.txt", Encoding.UTF8);
            if (e.ChatMessage.IsBroadcaster == true)
            {
                if (message[0].Equals("!del"))
                {
                    if (comm.Contains(message[1]))
                    {
                        int deger = Array.IndexOf(comm, message[1]);
                        list.RemoveAt(deger);
                        File.WriteAllLines("./command.txt", list);
                        list1.RemoveAt(deger);
                        File.WriteAllLines("./response.txt", list1);
                        client.SendMessage(e.ChatMessage.Channel, message[1] + "başarıyla Silindi!");




                    }

                }
            }






            foreach (string x in message)
            {
                string mess = x.ToLower();
                string[] command = File.ReadAllLines(@"./command.txt", Encoding.UTF8);
                string[] response = File.ReadAllLines(@"./response.txt", Encoding.UTF8);
                int a = command.Length;
                int i = 0;

                while (i < a)
                {
                   
                  


                    // (string)dataRow["comres"]
                    if (mess.Equals(command[i]))
                    {

                        client.SendMessage(e.ChatMessage.Channel, response[i] );



                    }
                    i++;
                }
                
                


                


           
           
                   
                





            }
            foreach (string x in message)
            {
                string mess = x.ToLower();
                string[] command = File.ReadAllLines(@"./ban.txt", Encoding.UTF8);
                
                int a = command.Length;
                int i = 0;

                while (i < a)
                {




                    // (string)dataRow["comres"]
                    if (mess.Equals(command[i]))
                    {

                        client.TimeoutUser(e.ChatMessage.Channel, e.ChatMessage.Username, TimeSpan.FromMinutes(1), "Küfür ve küfür kısaltmaları yasak!");



                    }
                    i++;
                }
















            }
        }


        private void Client_OnNewSubscriber(object sender, OnNewSubscriberArgs e)
        {
           if (e.Subscriber.SubscriptionPlan == SubscriptionPlan.Prime)
                client.SendMessage(e.Channel, $" {e.Subscriber.DisplayName} Prime abonelik ile Gurdlarin arasina karisti! theoAuu theoAuu Sizde Twitch Prime'a uye olarak abone olabilir ve ayricaliklarindan yararlanabilirsiniz!");
            else
                client.SendMessage(e.Channel, $" {e.Subscriber.DisplayName} Gurdların Arasına katıldı! theoAuu ");
        }
    }
}

and maybe assemblyinfo file can help u about that :

![image](https://user-images.githubusercontent.com/51324523/80917942-c9358880-8d6a-11ea-89ac-06ab1a8bd7b9.png)
`

**Comment by sydneyfunnelAIO** [comment]
and yeah published correctly.

**Comment by sydneyfunnelAIO** [comment]
oh we solved on stackoverflow there is the link : https://stackoverflow.com/questions/61569614/heroku-deploy-net-console-application/61571281#61571281

btw i have a question too.
how is must be procfile. beacause its 7/24 app. and it must work on worker

**Comment by sydneyfunnelAIO** [comment]
> oh we solved on stackoverflow there is the link : https://stackoverflow.com/questions/61569614/heroku-deploy-net-console-application/61571281#61571281
> 
> btw i have a few question too.
> how is must be procfile. beacause its 7/24 app. and it must work on worker
>  also i have a few text files for get some datas.
![image](https://user-images.githubusercontent.com/51324523/80919288-d86c0480-8d71-11ea-8abe-26f9bd25e772.png)

how can i add them too
