### ISSUE TITLE
How to deploy txt file to main folder

### ISSUE THREAD

**Issue by sydneyfunnelAIO** [jincod/dotnetcore-buildpack#114]
hello,
I created a local console app and deployed heroku(i had a question. solved with stackoverflow)

but i have a text files to takes datas. and how can i deploy them too ? 
![image](https://user-images.githubusercontent.com/51324523/80941924-4ce38980-8dec-11ea-8115-5636029aacbc.png)
there is my error screen.
where should my files been ?

**Comment by jincod** [comment]
Hi @sydneyfunnelAIO ,

You need to add the next lines to your `csproj` file.

``
<ItemGroup>
  <Content Include="config.txt">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
  </Content>
</ItemGroup>
```

**Comment by sydneyfunnelAIO** [comment]
it worked thx
