### ISSUE TITLE
state changed from up to crashed error

### ISSUE THREAD

**Issue by sydneyfunnelAIO** [jincod/dotnetcore-buildpack#115]
hello,
I created a console app(locally works).
but when i try start him. there is a error : 
![image](https://user-images.githubusercontent.com/51324523/80983497-46c5cb00-8e35-11ea-8498-484d33cedf81.png)
what should i do ?
there is my app: https://github.com/sydneyfunnelAIO/sydneyfunnelbot
it works on my computer

**Comment by jincod** [comment]
Try to update `Procfile`, change `web` to `worker`. More info here https://devcenter.heroku.com/articles/procfile#procfile-format

**Comment by sydneyfunnelAIO** [comment]
but already worker

**Comment by sydneyfunnelAIO** [comment]
i tried but same :(

**Comment by jincod** [comment]
Add more logging to your app and try\catch block

**Comment by sydneyfunnelAIO** [comment]
i didnt understand. can u explain it to me ?

**Comment by jincod** [comment]
Wrap this line https://github.com/sydneyfunnelAIO/sydneyfunnelbot/blob/master/Program.cs#L35 to try\catch block
