### ISSUE TITLE
Procfile problem

### ISSUE THREAD

**Issue by Coke21** [jincod/dotnetcore-buildpack#116]
Hi, I'm new to Heroku and I'm having problem with
```
2020-05-22T13:45:24.664460+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-05-22T13:45:24.690767+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-05-22T13:45:24.757254+00:00 heroku[web.1]: Process exited with status 137
2020-05-22T13:45:24.796970+00:00 heroku[web.1]: State changed from starting to crashed
```
I've seen similar issues in this repo, however, I'm not sure what to do if my app is only a console app, so no web app. I'm using a .NET Core and I believe I have to create a `Procfile` file with a worker.
 `worker: exec Program.cs` or `worker: Program.cs`
It didn't work. Where do I place this file, in the same location as `.sln`? I'm not sure what to put as a command here. It is a Discord bot app so it's not listening to any ports. I uploaded my app through automatic deployment on their website (via GitHub). How can I fix it?

**Comment by Coke21** [comment]
Ok, I'm moving forward, I have successfully put the Procfile in the right location and now Heroku properly reads the file, so now my Procfile looks like this `worker: exec Discord/Program.cs`, however, not I'm getting `Permission denied` error.

**Comment by jincod** [comment]
Hi @Coke21 

Your Procfile should be:

```
worker: cd $HOME/heroku_output && ./Discord
```

**Comment by Coke21** [comment]
Thank you so much for your quick response and help. Yes, it actually worked.
For people from the future:
Create a `Procfile` file in the main dictionary of your GitHub repo. So in the same location of e.g. `README.md` and `.gitignore`. Then put what @jincod typed above. Just specify the location and name of your folder. 
Thank you again for your help @jincod

**Comment by jincod** [comment]
More info about `Procfile` https://devcenter.heroku.com/articles/procfile#procfile-naming-and-location

Will update README
