### ISSUE TITLE
How safe is it to use this .NET Core buildpack for a production project?

### ISSUE THREAD

**Issue by Rhonage** [jincod/dotnetcore-buildpack#118]
Hey there. I'm part of a startup, and hoping to host my .NET Core API with Heroku. This will be eventually in production. I'm yet to encounter any issues with it during my testing, but just wanted to know if it's a terrible idea or not.
Thanks in advance.

**Comment by nbarbettini** [comment]
It's been rock-solid for me. I don't have any concerns about using it in production.

I made some tweaks, but that was driven by using Heroku CI (Testpack API) not any production instability.

**Comment by jincod** [comment]
Hi @Rhonage

The buildpack is only about building and doesn't influence on the production process.
