### ISSUE TITLE
.Net Core 2.0 Official Support ? 

### ISSUE THREAD

**Issue by timpur** [jincod/dotnetcore-buildpack#12]
Does this buildpack support the new core 2.0 just released?

**Comment by jincod** [comment]
Hi @timpur 

2.0.0-preview2-006497 is currently supported version. I'll plan to update to release 2.0.0 soon.

**Comment by timpur** [comment]
Awesome any time frame ? :)

**Comment by jincod** [comment]
@timpur ETA 2-3 days

**Comment by timpur** [comment]
Thanks.
Great work btw, Seems to just work with no problems (atm) :)

**Comment by jincod** [comment]
Hi @timpur 

I have updated buildpack to .NET Core 2.0.0. Could you try it? And if everything is ok, I'll close issue.

**Comment by timpur** [comment]
Testing now.

**Comment by timpur** [comment]
Seems to be working fine :)
