### ISSUE TITLE
Wrong SDK used on a Heroku app?

### ISSUE THREAD

**Issue by massimilianokraus** [jincod/dotnetcore-buildpack#121]
I'm working at a Blazor app (hosted mode), using .NET Core 3.1.7.

When I push my changes on Heroku via `git push my-app master`, these lines appear on the Console:
> remote: Welcome to .NET Core 3.1!
> remote: ---------------------
> remote: SDK Version: 3.1.101

Why is the 3.1.101 used instead of the latest (3.1.401)?
Is there something wrong with Heroku or with this buildpack?
Is there something I can do to udpate the .NET version used by Heroku?

**Comment by jincod** [comment]
Hi @massimilianokraus 

Here 2 options:
- Clear Heroku cache https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache
- Specify SDK version by env variables `DOTNET_SDK_VERSION` and `DOTNET_RUNTIME_VERSION` https://github.com/jincod/dotnetcore-buildpack/blob/master/bin/compile#L32-L33
- Use specific buildpack version https://github.com/jincod/dotnetcore-buildpack#previous-releases
