### ISSUE TITLE
I've added this buildpack in my heroku app but it seems to be throwing "Fatal error in Mono IL Linker"

### ISSUE THREAD

**Issue by helloitsm3** [jincod/dotnetcore-buildpack#124]
I'm currently trying to deploy me Blazor WASM app onto heroku with this buildpack but it doesn't seem to be running the app on heroku. I'm not very sure how to fix this.

![image](https://user-images.githubusercontent.com/13825491/91994110-c8d4ea80-ed68-11ea-9991-8eadd6c9545e.png)

**Comment by jincod** [comment]
Hello @helloitsm3 

2 options here:
- missed `FlappyBirdDemo.Web.dll`
- netstandard2.1. Which buildpack url do you use? I think you need `preview` branch.

**Comment by helloitsm3** [comment]
> 
> 
> Hello @helloitsm3
> 
> 2 options here:
> 
>     * missed `FlappyBirdDemo.Web.dll`
> 
>     * netstandard2.1. Which buildpack url do you use? I think you need `preview` branch.

1. I have FlappyBirdDemo.Web.dll in "bin/Debug/netstandard2.1" 
2. I'm currently using https://buildpack-registry.s3.amazonaws.com/buildpacks/jincod/dotnetcore.tgz

**Comment by jincod** [comment]
@helloitsm3 

Please use `https://github.com/jincod/dotnetcore-buildpack#net-core-preview-release`

**Comment by helloitsm3** [comment]
Is there a way to prevent the buildpack from automatically "cd" to heroku_output?

**Comment by jincod** [comment]
Create custom Procfile https://devcenter.heroku.com/articles/procfile#procfile-naming-and-location
