### ISSUE TITLE
Add support for Heroku-20

### ISSUE THREAD

**Issue by edmorley** [jincod/dotnetcore-buildpack#127]
Hi!

Heroku-20 beta was just released:
https://devcenter.heroku.com/changelog-items/1937

Trying this buildpack on a Heroku-20 app, the build currently fails with:

```
$ git init
$ h create --stack heroku-20 --buildpack https://github.com/jincod/dotnetcore-buildpack
$ touch Program.cs
$ git add -A && git commit -m '.' && git push heroku main
...
remote: -----> Core .NET app detected
remote: Need heroku-16 or heroku-18 stack
remote:  !     Push rejected, failed to compile Core .NET app.
```

From:
https://github.com/jincod/dotnetcore-buildpack/blob/dbff2e75c2bf2298a11db2593e526b5da4a6849a/bin/compile#L10-L13

Looking at the rest of the buildpack, it doesn't seem that stack-specific runtime binaries are used, so presumably added support for Heroku-20 should just mean updating the conditional above, and then adding to the makefile/CI:
https://github.com/jincod/dotnetcore-buildpack/blob/dbff2e75c2bf2298a11db2593e526b5da4a6849a/Makefile#L1-L5
https://github.com/jincod/dotnetcore-buildpack/blob/dbff2e75c2bf2298a11db2593e526b5da4a6849a/.github/workflows/main.yml#L10-L11

Many thanks :-)

**Comment by jincod** [comment]
Hello @edmorley,

Thank you for your contribution💪

I've added support for heroku-20

**Comment by edmorley** [comment]
@jincod Amazing, thank you!

One small tweak to the changes - there is no stack `heroku-14`, that stack is called `cedar-14` (`heroku-16` was the first to use the "heroku-" prefix):
https://github.com/jincod/dotnetcore-buildpack/blob/21520edd0518259409a98602eb62928276d1fef0/bin/compile#L10-L11
