### ISSUE TITLE
Referenced project not found when deploying

### ISSUE THREAD

**Issue by Rhonage** [jincod/dotnetcore-buildpack#128]
Hey all,

I'm having an issue where I have a referenced data layer project, which deploys fine when publishing locally - but not when using the Heroku buildpack.

The deploy works fine up until it can't find the referenced project.

```
Skipping project "/tmp/HavenAPI/Haven.Data/Haven.Data.csproj" because it was not found.        
remote: /tmp/codon/tmp/cache/dotnet/3.1.101/sdk/sdk/3.1.101/Microsoft.Common.CurrentVersion.targets(1875,5): warning : The referenced project '../HavenAPI/Haven.Data/Haven.Data.csproj' does not exist. [/tmp/build_3f1a3b65/Haven.Sender.csproj]        
remote: /tmp/codon/tmp/cache/dotnet/3.1.101/sdk/sdk/3.1.101/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Haven.Data". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/tmp/build_3f1a3b65/Haven.Sender.csproj]      
```

Has anyone had an issue with this? Thanks in advance.

**Comment by jincod** [comment]
Hi @Rhonage,

`Haven.Data.csproj` hasn't been commited to the repo. Make sure that everything is commited and the paths are correct

**Comment by Rhonage** [comment]
Wow @jincod  that was a very fast reply, thank you!

Unfortunately my setup is such that the Haven.Data project has it's own repo (as it's used by 2 separate projects, hence the segregation).

Will my setup not be compatible with your buildpack unless Haven.Data lives in the same repo?

**Comment by jincod** [comment]
> Will my setup not be compatible with your buildpack unless Haven.Data lives in the same repo?

Yes, and with any CI sustems. There is no magic to build the project without sources. 

The easiest way to use `Haven.Data` as nuget package.

**Comment by Rhonage** [comment]
Thank you @jincod , that helps a lot. Unfortunately creating a nuget package would expose my entire database connection strings etc, so that's not a viable option for me.

I'll look into a build build event that copies the Haven.Data project to the same repo :) 

Thanks again!

**Comment by jincod** [comment]
> Unfortunately creating a nuget package would expose my entire database connection strings etc, so that's not a viable option for me.

no, you do need to "hardcore" DB connection string. Use `appsettings.json` and Environment Variables. Please see this issue https://github.com/jincod/dotnetcore-buildpack/issues/33
