### ISSUE TITLE
Folder permissions after deployment.

### ISSUE THREAD

**Issue by lagseeing** [jincod/dotnetcore-buildpack#129]
Hello. Been trying to deploy an installation of [NopCommerce](https://www.nopcommerce.com/en) to try it out on my free tier plan.

But after everything works I get an error message about  the Kestrel not having enough permissions for some folders.

I read online that i have to make a .profile file with the permissions but I havent got any luck.

`    The ' account is not granted with Modify permission on folder '/app/heroku_output/bin'. Please configure these permissions.
    The ' account is not granted with Modify permission on folder '/app/heroku_output/logs'. Please configure these permissions.
`

Any ideas? this is my first time using your Buildpack.

**Comment by jincod** [comment]
Hi @lagseeing,

Heroku doesn't allow to write on FS after deployment https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted
