### ISSUE TITLE
Support for .NET 5

### ISSUE THREAD

**Issue by AmSmart** [jincod/dotnetcore-buildpack#131]
Will the buildpack support .NET 5 straightaway?

PS: I have been using this buildpack for a while now. It's absolutely lovely

**Comment by jgilchrist** [comment]
@AmSmart You can use .NET 5 by setting the `DOTNET_SDK_VERSION` and `DOTNET_RUNTIME_VERSION` environment variables to `5.0.100` and `5.0.0` respectively, until they become the default for the buildpack.

**Comment by AmSmart** [comment]
Thanks a lot. Well appreciated.

**Comment by jincod** [comment]
Hi there

```
heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack#v5.0.100
```

**Comment by AmSmart** [comment]
Thanks 🙏🙏🙏!
