### ISSUE TITLE
Can I use this buildpack for run multiple projects?

### ISSUE THREAD

**Issue by Gasyanich** [jincod/dotnetcore-buildpack#132]
Hello! I have sln with structure like this:
![image](https://user-images.githubusercontent.com/39405328/99914414-b5597000-2d16-11eb-8a0b-d9b6dc399732.png)

When I publish it to heroku only one project starts.
I want to run ASO.API and ASO.IdentityServer at the same time. Can I use this buildpack for do this? 
Thank you!

**Comment by jincod** [comment]
Hi @Gasyanich,

I haven't tried it yet. 

Check this approach https://help.heroku.com/CTFS2TJK/how-do-i-run-multiple-processes-on-a-dyno

**Comment by nbarbettini** [comment]
I assume that ASO.IdentityServer is intended to be internet-facing? Heroku only [routes traffic to `web` dynos](https://devcenter.heroku.com/articles/dynos#dyno-configurations) and you can't have more than 1. See: https://stackoverflow.com/questions/35538762/several-web-process-types-in-heroku

There are two ways you can work around this:
1. Publish your code to more than one Heroku app (one that runs the API project, and one that runs the IdentityServer project). They will need to be configured with different public URLs.
2. Much more complex: Use a single Heroku app that runs a reverse proxy as the "web" dyno and routes traffic internally to either project. I think it is possible, but I haven't done it. I'd recommend (1) as a starting point.
