### ISSUE TITLE
Do we need to manually restore tools?

### ISSUE THREAD

**Issue by sixpeteunder** [jincod/dotnetcore-buildpack#133]
Hello there @jincod 👋

I'm trying to deploy an app with v5.0.100 of the buildpack (ASP.NET 5 and EF Core 5 as well). However, the error I keep getting is:

> Run "dotnet tool restore" to make the "dotnet-ef" command available.

I never needed to do this in the past. Has this behaviour changed or am I doing something wrong?
Just to confirm, if it has changed, this would be the new block to add to `.csproj`, right?

```xml
<Target Name="PrePublishTarget" AfterTargets="Publish">
  <Exec Command="dotnet tool restore" />
  <Exec Command="dotnet ef database update" />
</Target>
```

I would be happy to send a pull request to document the new behaviour.

**Comment by jincod** [comment]
Hello @sixpeteunder,

You need to add `dotnet-tools.json`. Readme: https://github.com/jincod/dotnetcore-buildpack#enabling-automatic-migrations

Also may be useful https://github.com/jincod/dotnetcore-buildpack/pull/104?

**Comment by sixpeteunder** [comment]
I have a tool manifest set up, and this solved my issue:

> ```xml
> ​<​Target​ ​Name​=​"​PrePublishTarget" AfterTargets=​"​Publish​"​>
>  <​Exec​ ​Command​=​"​dotnet tool restore​"​ />
>  <​Exec​ ​Command​=​"dotnet ef database update​"​ />
> </​Target​>
```

My folder structure is a solution with three projects, and only one, the one I'm interested in deploying, has a tool manifest.
