### ISSUE TITLE
HTTPS department point (Cookie.SameSite = SameSiteMode.None)

### ISSUE THREAD

**Issue by netnr** [jincod/dotnetcore-buildpack#134]
This is the current deployment command
`web cd $HOME/heroku_output && ./Netnr.Blog.Web`

New version of Chrome can't use SameSiteMode.None on http,
Use https or remove SameSiteMode.None

Does the deployment command need to be modified on heroku or from dotnetcore-buildpack?

configure HTTPS, installation command: `dotnet dev-certs https`
Specify deployment `./Netnr.Blog.Web https://*:5000`

**Comment by jincod** [comment]
Hello @netnr,

Heroku offers https by default and you don't need dev certs. Example, https://aspnetcoredemoapp.herokuapp.com/

How to configure https://github.com/jincod/AspNetCoreDemoApp/blob/master/src/AspNetCoreDemoApp/Startup.cs

**Comment by netnr** [comment]
This is the access output log

```
Starting process with command `cd /app/heroku_output && ./Netnr.Blog.Web`
User profile is available. Using '/app/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
with creation date 2020-12-21 04:52:03Z, activation date 2020-12-21 04:52:03Z, and expiration date 2021-03-21 04:52:03Z.
may be persisted to storage in unencrypted form.
Writing data to file '/app/.aspnet/DataProtection-Keys/key-2b838bbf-ff70-421a-956b-8b33196fa248.xml'.
Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
Entity Framework Core 5.0.1 initialized 'ContextBase' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled MaxPoolSize=99 StoreName=MemoryDB 
Saved 0 entities to in-memory store.
Saved 1468 entities to in-memory store.

Now listening on: http://[::]:5540
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: /app/heroku_output
State changed from starting to up
Request starting HTTP/1.1 GET http://www.netnr.eu.org/
```

Now listening on: http://[::]:5540
Should be listening https://[::]:5540

**Comment by jincod** [comment]
Correct, Heroku terminates https traffic.

Please check this issue https://github.com/jincod/dotnetcore-buildpack/issues/81
