### ISSUE TITLE
Feature request: heroku-20

### ISSUE THREAD

**Issue by omerhijazi404** [jincod/dotnetcore-buildpack#140]
This is a feature request for asp.net core for heroku-20 stack

**Comment by jincod** [comment]
@omerhijazi404 it already has. 

What the issue do you have?

**Comment by omerhijazi404** [comment]
```
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: jincod/dotnetcore
remote: -----> ASP.NET Core app detected
remote: Need heroku-16 or heroku-18 stack
remote:  !     Push rejected, failed to compile ASP.NET Core app.
```
It's not working on heroku-20

**Comment by jincod** [comment]
Hello @omerhijazi404 

I see, it's `jincod/dotnetcore` version.

It has been updated now.

Try to build again and clear the cache if need it

Thank you for you feedback

**Comment by omerhijazi404** [comment]
Thank you, it works!
