### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by gabrielareia** [jincod/dotnetcore-buildpack#142]
Hello, great application!

I don't know if this is really the place to post this, if it isn't I'm sorry. But I need to set some environment variables (JWT credentials) and I'd like to set them in Heroku directly. How can I access this environment variable from inside the code? Is there a way to do this with dotnetcore-buildpack? Or I don't even need to? I tried to search but I couldn't find anything about dotnet.

**Comment by jincod** [comment]
Hello @gabrielareia 

See this article https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#environment-variables
