### ISSUE TITLE
Get rid of "cd" in Prodfile for interoperability with herokuish

### ISSUE THREAD

**Issue by DCNick3** [jincod/dotnetcore-buildpack#145]
Herokuish is an implementation of heroku buildpacks logic used, for example, in Dokku - a self-hosted PaaS providing similar features to heroku.

This buildpack seems to work fine with it, but, unfortunately, it [uses exec](https://github.com/gliderlabs/herokuish/blob/bd3211657125cd66fe297c42a61feaf288f9d25e/include/procfile.bash#L58) to run the command that is put in `Procfile`, which fails miserably when used with `Procfile` generated by this project, containing something like `cd $HOME/heroku_output && ./app_executable`. If it is replaced with `$HOME/heroku_output/app_executable` - it works fine.

I think it might be a good idea to change it so that it will work with herokuish and dokku.

As a workaround one can use custom Procfile with something like `web: $HOME/heroku_output/app_executable` in it.

**Comment by DCNick3** [comment]
Seems that some user has already experienced this error in dokku/dokku#3253

**Comment by jrhodnik** [comment]
I'm also running into this issue. @DCNick3 did you happen to resolve this, or should I try to figure out what's what?

**Comment by jrhodnik** [comment]
Oops, I see what you mean. [I forked](https://github.com/jrhodnik/dotnetcore-buildpack) this repo and did the suggestions above however this does mess with the working directory which will likely break apps. Adding something like `Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location));` to the entry point resolves this but it is still a breaking change so it's probably not worth a PR here. As suggested above the best solution is for *herokuish* to change how they handle Procfile execution.

**Comment by DCNick3** [comment]
I've also tried playing around with `bash -c 'command'`, but it didn't work for some reason (maybe I am stupid or shell escaping gone haywire)

`web: $HOME/heroku_output/app_executable` worked for me because I don't care about the working directory, but yeah, if you need it - you can change it in C# as a workaround

**Comment by jrhodnik** [comment]
Just got a chance to test this. Here's the result. Is this my environment, or something else maybe?

```bash
remote:        Add web process to Procfile
remote:        Override Procfile for herokuish
remote:        Using release configuration from last framework (ASP.NET Core).
remote:        -----> Discovering process types
remote:        Procfile declares types -> web
remote: -----> Releasing rap-master...
remote: -----> Checking for predeploy task
remote:        No predeploy task found, skipping
remote: -----> Checking for release task
remote:  !     process names must be unique, line 2
remote: 2021/10/07 22:06:32 exit status 1
remote: -----> App Procfile file found
remote:        No release task found, skipping
remote: -----> App Procfile file found
remote:  !     process names must be unique, line 2
remote: 2021/10/07 22:06:36 exit status 1
remote:  !     exit status 1
remote: 2021/10/07 22:06:36 exit status 1
remote: 2021/10/07 22:06:36 exit status 1
remote: 2021/10/07 22:06:36 exit status 1
```

**Comment by jincod** [comment]
Thank you @jrhodnik 

It should be fixed now

**Comment by jincod** [comment]
Merged to master. Updated [README](https://github.com/jincod/dotnetcore-buildpack#herokuish-support)

Thank you for your contribution!
