### ISSUE TITLE
 Permissions on directories

### ISSUE THREAD

**Issue by david127cu** [jincod/dotnetcore-buildpack#152]
Hello.
I installed this buildpack and test the hello world (worked").
Put i need to execute chmod 777 -R Storage, to change my folder permisson.
the script executed successful, but after deployed, when I execute: heroku run "ls -la" to see the permissions, the permissions aren't set.
Running the command in the Procfile file doesn't work either.

Can you help me?

**Comment by jincod** [comment]
Hello @david127cu 

Please see the issue https://github.com/jincod/dotnetcore-buildpack/issues/129

**Comment by david127cu** [comment]
Thanks
