### ISSUE TITLE
Problem when using Web API with swagger

### ISSUE THREAD

**Issue by atsouza** [jincod/dotnetcore-buildpack#157]
I'm using the buildpack to run a Web API on heroku with swagger, but when I deploys it to heroku I get this message when try to open it 

![image](https://user-images.githubusercontent.com/9975911/146666624-35407782-bd8d-4e96-a869-08f46b4b3a93.png)

It is in portuguese but it says the page cannot be found. What I did wrong? I just created the default exemple to make some tests. 

(using .net core 5)

**Comment by jincod** [comment]
Hello @atsouza 

Not enough information to help you. Does it work locally?

Is this project public?

**Comment by atsouza** [comment]
It works localy. The project is for test purpose only.

**Comment by jincod** [comment]
Please check this project https://github.com/jincod/AspNetCoreDemoApp
