### ISSUE TITLE
Dotnet 5.0.404 security updates

### ISSUE THREAD

**Issue by konradbartecki** [jincod/dotnetcore-buildpack#158]
Hey Vadim, thank you for you work. 
I know .NET 5 is reaching the end of the support soon (in May 2022), but there are some security updates aka .NET 5.0.404.
Do you have any plans and ideas, how to tackle the support of the most recent .NET 6 along with the security updates for .NET 5? branches?

**Comment by jincod** [comment]
Hello @konradbartecki 

I've created branch v5.
```
heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack#v5
```

**Comment by konradbartecki** [comment]
Works, thanks a lot!
