### ISSUE TITLE
How to install p7zip-full etc.

### ISSUE THREAD

**Issue by david127cu** [jincod/dotnetcore-buildpack#160]
How to "install" p7zip-full, unzip, busybox  etc. If you needed?

**Comment by jincod** [comment]
Hello @david127cu,

The best way to fork and change the compile\lib files. Something like this https://github.com/jincod/dotnetcore-buildpack/commit/053ddfb26a80ee82d4c27fefd89f88f6e0b72943#diff-4da89516c7ffa7482d17eb0dd7a21f24ce35411886f610b3dd7cf1815e70b506L44

**Comment by david127cu** [comment]
Thanks
