### ISSUE TITLE
How to use it as buildpack for a specific version of .net core?

### ISSUE THREAD

**Issue by bereav** [jincod/dotnetcore-buildpack#161]
I read that if I want to use it for a specific version of .net core I have to use this syntax:
`https://github.com/jincod/dotnetcore-buildpack#version`

I tried:
https://github.com/jincod/dotnetcore-buildpack#6.0.1

It failed during deployment.
How do I specify the version of the buildpack that will work with .net core 6.0.1?

**Comment by jincod** [comment]
Hello @bereav 

Please check this https://github.com/jincod/dotnetcore-buildpack/issues/131#issuecomment-726409101

**Comment by fabriciomurta** [comment]
I've missed a git-tag here for v6.0.201 (so I can choose when I want to update once a new update is out).

By the way for what OP suggests he want to select the runtime version, whereas this repo has some tags regarding the SDK version. It should be fine, just check what runtime the given tag uses.

@bereav you can check any of these [tags on this repo](https://github.com/jincod/dotnetcore-buildpack/tags) (the leading `v` is taken into account). To see which runtime version it uses, just check tag's `bin/compile` file (for example [for v6.0.100 tag](https://github.com/jincod/dotnetcore-buildpack/blob/v6.0.100/bin/compile#L33-L34).

Relying on the git tag should be better than overriding the environment variables as the latest state of the repo could have changes that would prevent older versions to work.
