### ISSUE TITLE
Wrong project type: web instead of console

### ISSUE THREAD

**Issue by xzxzxc** [jincod/dotnetcore-buildpack#163]
I have an application with a .csproj file that starts with `<Project Sdk="Microsoft.NET.Sdk">`. Because it's `Microsoft.NET.Sdk` and not `Microsoft.NET.Sdk.Web` it should be treated as console application, not web. 
But when I deploy, I see next in logs
```
Discovering process types
Procfile declares types -> web
```
So program fails after start with
```
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

**Comment by jincod** [comment]
Hello @xzxzxc,

Please check the issue https://github.com/jincod/dotnetcore-buildpack/pull/151

**Comment by xzxzxc** [comment]
@jincod thank you!
