### ISSUE TITLE
Using Buildpack for multiple projects.

### ISSUE THREAD

**Issue by iamstan13y** [jincod/dotnetcore-buildpack#165]
I need to understand what this means:

![image](https://user-images.githubusercontent.com/46853837/160802902-b332f4d2-e9f5-4604-9322-0739a0417420.png)

Does it mean I have to specify the project I want to build, and if so how do I so and where?
I recently deployed 2 projects (Web APIs) on Heroku, **projectA and projectB**, and they're both using the same repo. Now the problem that arises is projectA is using projectB's files and vice-versa, such that after deployment I'm seeing the deployments vice-versa...

**Comment by jincod** [comment]
How to setup env vars https://devcenter.heroku.com/articles/config-vars

PROJECT_FILE and PROJECT_NAME allows specify project to deploy

PROJECT_FILE =/src/ProjectA/ProjectA.csproj
PROJECT_NAME=ProjectA

**Comment by iamstan13y** [comment]
I think that's quite understandable. Saved hours of stabbing in the dark❤
