### ISSUE TITLE
Issue publishing additional assets

### ISSUE THREAD

**Issue by imerzan** [jincod/dotnetcore-buildpack#167]
Hello! Thank you for your work on this buildpack ,it is very useful.

I encountered some odd behavior when publishing with your buildpack (spent most of last night, and this morning trying to resolve)

For some reason I am unable to publish additional files when pushing to heroku. I've scoured the issues here (like https://github.com/jincod/dotnetcore-buildpack/issues/155 ) and tried as many .csproj combinations as possible. It seems really inconsistent on what people get to work.

This morning I was able to get the following code to work on a text file that only contains "Hello world!" 
```csharp
  <ItemGroup>
    <Content Include="Test.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

Verified it actually uploaded. Looked good.

I then tried to use my actual intended file (152 Kb binary file) and keep getting
`error MSB3030: Could not copy the file "/tmp/build_7398a74a/filename" because it was not found. [/tmp/build_7398a74a/MyApp.csproj]`

Then I tried to go back and use the same code that previously worked for Test.txt, and I am now getting the same error again.

It seems REALLY inconsistent on what gets included and what doesn't.

If I try publish locally using `dotnet publish -o testbuild` the files get included OK.

**Any idea how I can get a single asset file to upload to my build directory when pushing to heroku?**

I am testing using the most basic ASP.NET Template, Program.cs is as follows
```csharp
namespace MyApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            var app = builder.Build();

            app.MapGet("/", () => "Hello World!");

            app.Run();
        }
    }
}
```

.csproj contents:
```csharp
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Test.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
```

**Comment by imerzan** [comment]
Still not sure why this happens, but taking a look at 
https://stackoverflow.com/questions/62435444/heroku-cannot-find-my-file-on-deployment-but-it-works-locally

I was able to use 
```
$ heroku plugins:install heroku-builds
$ heroku builds:cache:purge -a appname
```

After this I add files & commit/publish, and then it includes additional assets. Very peculiar.

**Comment by jincod** [comment]
Hello @imerzan 

Thank you for your feedback!

Is everything fine now? Can we close the issue?

**Comment by imerzan** [comment]
Will go ahead and close it for now as it's no longer a pressing issue (I am still curious why this happens though)
