### ISSUE TITLE
Skipping projects because it was not found. Solution with api and other projects referenced

### ISSUE THREAD

**Issue by aerlijman** [jincod/dotnetcore-buildpack#174]
Hi, I am testing this buildpack but getting the following errors. It's a solution with an API that has dependencies in other projects.
This compiles fine in VS and VS code command line with dotnet build.
Ideas?

-----> Building on the Heroku-20 stack
-----> Using buildpack: https://github.com/jincod/dotnetcore-buildpack
-----> Core .NET app detected
> Installing dotnet
-----> Removing old cached .NET version
-----> Fetching .NET SDK
-----> Fetching .NET Runtime
-----> Export dotnet to Path
-----> Project File
> /tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj
-----> Project Name
> BuberDinner.Api
> publish /tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj for Release on heroku_output
Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.301
----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  Skipping project "/tmp/build_b629b5f5/BuberDinner.Contracts/BuberDinner.Contracts.csproj" because it was not found.
  Skipping project "/tmp/build_b629b5f5/BuberDinner.Application/BuberDinner.Application.csproj" because it was not found.
  Skipping project "/tmp/build_b629b5f5/BuberDinner.Infrastructure/BuberDinner.Infrastructure.csproj" because it was not found.
  Skipping project "/tmp/build_b629b5f5/BuberDinner.Contracts/BuberDinner.Contracts.csproj" because it was not found.
  Skipping project "/tmp/build_b629b5f5/BuberDinner.Application/BuberDinner.Application.csproj" because it was not found.
  Skipping project "/tmp/build_b629b5f5/BuberDinner.Infrastructure/BuberDinner.Infrastructure.csproj" because it was not found.
  Restored /tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj (in 2.37 sec).
/tmp/codon/tmp/cache/dotnet/6.0.301/sdk/sdk/6.0.301/Microsoft.Common.CurrentVersion.targets(2066,5): warning : The referenced project '../BuberDinner.Contracts/BuberDinner.Contracts.csproj' does not exist. [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/codon/tmp/cache/dotnet/6.0.301/sdk/sdk/6.0.301/Microsoft.Common.CurrentVersion.targets(2066,5): warning : The referenced project '../BuberDinner.Application/BuberDinner.Application.csproj' does not exist. [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/codon/tmp/cache/dotnet/6.0.301/sdk/sdk/6.0.301/Microsoft.Common.CurrentVersion.targets(2066,5): warning : The referenced project '../BuberDinner.Infrastructure/BuberDinner.Infrastructure.csproj' does not exist. [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/build_b629b5f5/BuberDinner.Api/Controllers/AuthenticationController.cs(1,19): error CS0234: The type or namespace name 'Application' does not exist in the namespace 'BuberDinner' (are you missing an assembly reference?) [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/build_b629b5f5/BuberDinner.Api/Controllers/AuthenticationController.cs(2,19): error CS0234: The type or namespace name 'Contracts' does not exist in the namespace 'BuberDinner' (are you missing an assembly reference?) [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/build_b629b5f5/BuberDinner.Api/Program.cs(1,19): error CS0234: The type or namespace name 'Application' does not exist in the namespace 'BuberDinner' (are you missing an assembly reference?) [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/build_b629b5f5/BuberDinner.Api/Program.cs(2,19): error CS0234: The type or namespace name 'Infrastructure' does not exist in the namespace 'BuberDinner' (are you missing an assembly reference?) [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/build_b629b5f5/BuberDinner.Api/Controllers/AuthenticationController.cs(20,35): error CS0246: The type or namespace name 'RegisterRequest' could not be found (are you missing a using directive or an assembly reference?) [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/build_b629b5f5/BuberDinner.Api/Controllers/AuthenticationController.cs(37,32): error CS0246: The type or namespace name 'LoginRequest' could not be found (are you missing a using directive or an assembly reference?) [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/build_b629b5f5/BuberDinner.Api/Controllers/AuthenticationController.cs(12,22): error CS0246: The type or namespace name 'IAuthenticationService' could not be found (are you missing a using directive or an assembly reference?) [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
/tmp/build_b629b5f5/BuberDinner.Api/Controllers/AuthenticationController.cs(14,37): error CS0246: The type or namespace name 'IAuthenticationService' could not be found (are you missing a using directive or an assembly reference?) [/tmp/build_b629b5f5/BuberDinner.Api/BuberDinner.Api.csproj]
 !     Push rejected, failed to compile Core .NET app.
 !     Push failed

**Comment by jincod** [comment]
Hello @aerlijman 

Have you commited these project to the repo?
BuberDinner.Contracts.csproj
BuberDinner.Application.csproj
BuberDinner.Infrastructure.csproj
BuberDinner.Contracts.csproj
BuberDinner.Application.csproj
BuberDinner.Infrastructure.csproj

**Comment by aerlijman** [comment]
Sure.. this is the zip downloaded from Git. It´s a tutorial for Clean architecture I am following.
[BuberDinner-main.zip](https://github.com/jincod/dotnetcore-buildpack/files/9063608/BuberDinner-main.zip)

**Comment by jincod** [comment]
Hello @aerlijman 

Please pay attention on csproj names. It's case sensitive

```
buberDinner.Contracts.csproj -> BuberDinner.Contracts.csproj
buberDinner.Application.csproj -> BuberDinner.Application.csproj
buberDinner.Infrastructure.csproj -> BuberDinner.Infrastructure.csproj
```

**Comment by aerlijman** [comment]
holy cows Batman! that was it!
Thx a lot and hope this may help others.
