### ISSUE TITLE
publish gives error The type or namespace name 'Android'...

### ISSUE THREAD

**Issue by anderslm** [jincod/dotnetcore-buildpack#18]
A newly created Web API project fails with:

> .....
> Restore completed in 4.8 sec for /tmp/build_831e056b987c006a19ae77c35db9bb78/VikarBackend.csproj.
> 
> publish /tmp/build_831e056b987c006a19ae77c35db9bb78/VikarBackend.csproj
> 
> Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
> 
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> dotnet/sdk/NuGetFallbackFolder/microsoft.identitymodel.clients.activedirectory/3.14.1/src/src/ADAL.PCL.Android/Resources/Resource.Designer.cs(12,20): error CS0400: The type or namespace name 'Android' could not be found in the global namespace (are you missing an assembly reference?) [/tmp/build_831e056b987c006a19ae77c35db9bb78/VikarBackend.csproj]
> 
> dotnet/sdk/NuGetFallbackFolder/microsoft.identitymodel.clients.activedirectory/3.14.1/src/src/ADAL.PCL.Android/Resources/Resource.Designer.cs(12,122): error CS0246: The type or namespace name 'IsApplication' could not be found (are you missing a using directive or an assembly reference?) [/tmp/build_831e056b987c006a19ae77c35db9bb78/VikarBackend.csproj]
> ....

The project:
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
     <TargetFramework>netcoreapp2.0</TargetFramework>
   </PropertyGroup>
   <ItemGroup>
     <Folder Include="wwwroot\" />
   </ItemGroup>
   <ItemGroup>
     <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
   </ItemGroup>
 </Project>`

**Comment by jincod** [comment]
Hi @anderslm 

Thank you for report. I'll investigate this.

**Comment by jincod** [comment]
I think https://github.com/jincod/AspNet5DemoApp/issues/4 has same problem

**Comment by jincod** [comment]
Hi @anderslm 

I've updated buildpack: changed dotnet installation path. Could you please test it?
