### ISSUE TITLE
.NET Core 5 & React App heroku buildpack issue

### ISSUE THREAD

**Issue by ardithyseni** [jincod/dotnetcore-buildpack#181]
Hello, I am trying to deploy a .NET Core 5 & React App to Heroku using the jincod dotnetcore buildpack, and I'm not sure if I'm copying the right link, which is   [heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack#version]().
My dotnet --version is 5.0.201, and I get this error:
```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: https://github.com/jincod/dotnetcore-buildpack#version
remote:  !     error fetching custom buildpack https://github.com/jincod/dotnetcore-buildpack#version
remote: 
remote:  !     Push failed
remote: Verifying deploy....
remote: 
remote: !       Push rejected
```

Also – I tried using Heroku 20 stack and the link  heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack#v5.0.201 -- But I still get A LOT OF LINES of this error `error NU3037: Package 'Microsoft.IdentityModel.Protocols 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.`
Can anyone help me, thanks!

**Comment by ardithyseni** [comment]
The terminal when I use `heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack#v5.0.100`

remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: https://github.com/jincod/dotnetcore-buildpack#v5.0.100
remote: -----> ASP.NET Core app detected
remote: > Installing dotnet
remote: -----> Removing old cached .NET version
remote: -----> Fetching .NET SDK
remote: -----> Fetching .NET Runtime
remote: -----> Export dotnet to Path
remote: -----> Project File
remote: > /tmp/build_7ef456f7/API/API.csproj
remote: -----> Project Name
remote: > API
remote: > publish /tmp/build_7ef456f7/API/API.csproj for Release on heroku_output
remote: 
remote: Welcome to .NET 5.0!
remote: ---------------------
remote: SDK Version: 5.0.100
remote:
remote: ----------------
remote: Installed an ASP.NET Core HTTPS development certificate.
remote: To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
remote: Learn about HTTPS: https://aka.ms/dotnet-https
remote: ----------------
remote: Write your first app: https://aka.ms/dotnet-hello-world
remote: Find out what's new: https://aka.ms/dotnet-whats-new
remote: Explore documentation: https://aka.ms/dotnet-docs
remote: Report issues and find source on GitHub: https://github.com/dotnet/core
remote: Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
remote: --------------------------------------------------------------------------------------
remote: Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
remote: Copyright (C) Microsoft Corporation. All rights reserved.
remote:
remote:   Determining projects to restore...
remote: /tmp/build_7ef456f7/API/API.csproj : error NU3028: Package 'Microsoft.NETCore.Platforms 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
remote: /tmp/build_7ef456f7/API/API.csproj : error NU3037: Package 'Microsoft.NETCore.Platforms 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
remote: /tmp/build_7ef456f7/API/API.csproj : error NU3028: Package 'Microsoft.NETCore.Platforms 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
remote: /tmp/build_7ef456f7/API/API.csproj : error NU3037: Package 'Microsoft.NETCore.Platforms 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature validity period has expired.
remote: /tmp/build_7ef456f7/API/API.csproj : error NU3028: Package 'Microsoft.AspNetCore.App.Runtime.linux-x64 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
remote: /tmp/build_7ef456f7/API/API.csproj : error NU3037: Package 'Microsoft.AspNetCore.App.Runtime.linux-x64 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
.
.
.
.

**Comment by jincod** [comment]
@ardithyseni 

.NET SDK 6.0 works for .net core 5 app as well. Try to use latest version:
```
heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack
```

**Comment by ardithyseni** [comment]
@jincod thank you thank you thank you
