### ISSUE TITLE
Changing port of ASP.net core application running on Heroku with dotnetcore-buildpack

### ISSUE THREAD

**Issue by alphadelta987** [jincod/dotnetcore-buildpack#182]
Hi,

I've been using your build pack for 2 years and it's worked fantastically. Do you know how to change the port on heroku that an asp.net core web application is running on?

Kind regards,

David

**Comment by jincod** [comment]
Hello @alphadelta987,

You can't change the port. Here more info https://devcenter.heroku.com/articles/dynos#web-dynos
