### ISSUE TITLE
Is possible to use apt-get install

### ISSUE THREAD

**Issue by renerlemes** [jincod/dotnetcore-buildpack#183]
Is possible to install libgdiplus before or after the project be compiled?
I would to include the command **apt-get install libgdiplus**

**Comment by renerlemes** [comment]
@jincod it's not the same issue.
The application is working fine but I have one problem. I´m using Telerik Report which needs the **libgdiplus** to work. And I thought I'd fork your project and add these commands that I need to install the library. Could you help me with this?

The application working

https://rener-teste1.herokuapp.com
![image](https://user-images.githubusercontent.com/2191533/198045340-d27795c0-5cdb-4a76-a597-5a2b9ffc5610.png)

**Comment by jincod** [comment]
@renerlemes try something like this https://github.com/renerlemes/dotnetcore-buildpack/commit/053ddfb26a80ee82d4c27fefd89f88f6e0b72943#diff-a64a7d9b82578ca3053416d56631a61e0ceabed87619415663030e3842429e05L34

**Comment by renerlemes** [comment]
@jincod tks for this solution. now it´s working! why this function was removed?

**Comment by jincod** [comment]
@renerlemes these packages became not-required since .net core 2.1

**Comment by renerlemes** [comment]
@jincod the problem is that the lib installations run in the build and not in the runtime
