### ISSUE TITLE
.NET 7 Build Broken with .NET 8 upgrade

### ISSUE THREAD

**Issue by ampossardt** [jincod/dotnetcore-buildpack#188]
I see there's a merged PR for upgrading to .NET 8, but there's no tagged release for .NET 7 so this newest update breaks my .NET 7 build in heroku. Is there a tag planned for .NET 7 so that I don't have to upgrade .NET to continue using this?

```
[/tmp/build_da5deca9/Core/Core.csproj]
  Core -> /tmp/build_da5deca9/Core/bin/Release/net7.0/linux-x64/Core.dll
  Core -> /tmp/build_da5deca9/heroku_output/
  Build started...
  Build succeeded.
  You must install or update .NET to run this application.
  
  App: /app/.nuget/packages/dotnet-ef/7.0.12/tools/net6.0/any/tools/netcoreapp2.0/any/ef.dll
  Architecture: x64
  Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
  .NET location: /tmp/codon/tmp/cache/dotnet/8.0.100/sdk/
  
  The following frameworks were found:
    8.0.0 at [/tmp/codon/tmp/cache/dotnet/8.0.100/sdk/shared/Microsoft.NETCore.App]
  
  Learn more:
  https://aka.ms/dotnet/app-launch-failed
  
  To install missing framework, download:
  https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=linux-x64&os=ubuntu.22.04
/tmp/build_da5deca9/Core/Core.csproj(31,2): error MSB3073: The command "dotnet ef database update" exited with code 150.
 !     Push rejected, failed to compile Core .NET app.
 !     Push failed
```

Additionally, with these tags, what's proper format for the URL as should be added to heroku? I don't quite get the readme that says to use 'https://github.com/jincod/dotnetcore-buildpack#version' because it doesn't actually point to anything different than the current version.

**Comment by ampossardt** [comment]
I was able to get this working using the config variables within heroku to specify the sdk/runtime versions - originally i didn't think this was working but I didn't have appropriate versions set.

I'll leave this open in case a new tag should be created anyway.

**Comment by jincod** [comment]
Hi @ampossardt 

I've created the tag `v7.0.401`.

You can try to specify `DOTNET_ROLL_FORWARD=LatestMajor`.

P.S.: master contains the latest .NET Core release (not preview). So the best way to specify with required tag.

**Comment by ampossardt** [comment]
@jincod thank you!
