### ISSUE TITLE
Investigate reason of huge slug size

### ISSUE THREAD

**Issue by jincod** [jincod/dotnetcore-buildpack#19]
Warning: Your slug size exceeds our soft limit (468 MB) which may affect boot time.

https://github.com/jincod/AspNet5DemoApp/issues/4#issuecomment-326499671

**Comment by hbbhaumikpatel** [comment]
**Can we deploy only publish version?**

**How to clear slug?**

![image](https://user-images.githubusercontent.com/10570010/30048697-12c0a8ce-9235-11e7-8a65-ca2b91b8a62f.png)

**Multi Project support, If yes then How? Please provide detail or steps.**

**Comment by jincod** [comment]
> Can we deploy only publish version?
Buildpack deploys only published version from `/app/heroku_output`.

> How to clear slug?
Almost full slug size filled by .Net Core bin's and NuGetFallbackFolder. I have no idea how optimize it now

> Multi Project support, If yes then How? Please provide detail or steps.
What do you mean? Could you please explain?

**Comment by lppkarl** [comment]
I have made a PR of it, please check if it's useful, thank you 😄

**Comment by hbbhaumikpatel** [comment]
Thank you @lppkarl 

@jincod Can you please accept PR request from @lppkarl. So I can test.

**Comment by jincod** [comment]
Hi @hbbhaumikpatel 

I've created feature-branch. To test this PR, you need change buildpack url to https://github.com/jincod/dotnetcore-buildpack#feature/reduce-slug-size

**Comment by jincod** [comment]
https://github.com/jincod/dotnetcore-buildpack/blob/8f37358a54f5b347c7aa6e939d2247ba8e65378d/bin/compile#L28

Slug size will be reduced
