### ISSUE TITLE
Unable to build .NET 7

### ISSUE THREAD

**Issue by ampossardt** [jincod/dotnetcore-buildpack#194]
I just noticed that my builds today are failing despite not changing anything within my heroku setup.

Error i'm receiving while attempting to build:

```
-----> Building on the Heroku-22 stack
-----> Using buildpack: https://github.com/jincod/dotnetcore-buildpack
-----> Core .NET app detected
/tmp/codon/tmp/buildpacks/b2aac292d9949a681f84448317f66d5d1b64ca01/bin/compile: line 33: unexpected EOF while looking for matching `}'
 !     Push rejected, failed to compile Core .NET app.
 !     Push failed
```

Currently I'm running:
Runtime version   7.0.13
SDK version          7.0.403

My build runs fine locally so I'm not sure what else this issue could be other than the buildpack having some issue.

**Comment by bolst** [comment]
Also having this issue on .NET 8

**Comment by jincod** [comment]
Hi there,

It was a typo. I've pushed the hot fix now.
