### ISSUE TITLE
App not compatible with buildpack

### ISSUE THREAD

**Issue by bob19831** [jincod/dotnetcore-buildpack#21]
Running `git push heroku master` gives me the following error:
```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://github.com/jincod/dotnetcore-buildpack
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
```

My project is not at the root of the repository:
```
/client
/server
  - App.API.csproj
```

So I have specified a `.deployment` config file:
```
[config]
project = server/App.API
```

But I still can't get the buildpack to push to heroku.

**Comment by jincod** [comment]
Hi @bob19831 

`.deployment` file ignores by my buildpack.

Buildpack detect `Startup.cs` file https://github.com/jincod/dotnetcore-buildpack/blob/5e4301fc7b22fd1df69b10f255d4606fe7fca57b/bin/detect#L4. It's required to setup project.

So If you add `Startup.cs` to `/server/Startup.cs` buildpack can detect asp.net core app.

**Comment by jincod** [comment]
Hi @bob19831 

We've added support `PROOJECT_NAME` and `PROJECT_FILE` environment variables. Maybe it can help you https://github.com/jincod/dotnetcore-buildpack/pull/23
