### ISSUE TITLE
Any example for already published app?

### ISSUE THREAD

**Issue by CoderProject** [jincod/dotnetcore-buildpack#24]
Hi, I am totally new to heroku and this buildpack stuff. Could someone provide a fully working example with an already published app.

Currently I'm using your [this](https://github.com/jincod/AspNet5DemoApp) example but I don't like to push all project to heroku.

I would like to first publish my app to a folder then deploy this folder to heroku using git or dropbox. Is this somehow possible? What should files like dockerfile, app.json, appveyor.yml, run.sh, etc contain?

**Comment by jincod** [comment]
Hi @CoderProject 

> Could someone provide a fully working example with an already published app.
> Currently I'm using your this example but I don't like to push all project to heroku.

It's good example which demonstrate many Heroku features.

> I would like to first publish my app to a folder then deploy this folder to heroku using git or dropbox. 

It's wrong way. You should push source code to repo (not bin's and artifacts). Read this article about Heroku https://devcenter.heroku.com/articles/how-heroku-works

> What should files like dockerfile, app.json, appveyor.yml, run.sh, etc contain?

Only `app.json` Heroku related (more info https://devcenter.heroku.com/articles/app-json-schema).
