### ISSUE TITLE
Successfully build but no web pages found

### ISSUE THREAD

**Issue by kodelapan** [jincod/dotnetcore-buildpack#25]
Hi, i'm trying to build asp.net core 2.0 on heroku. Build success on command line, but when open heroku app, it return "No Web Pages Found". This project also use database Postgresql. This is my project link on github https://github.com/kodelapan/coffeemaker

My heroku console
![screenshot_105](https://user-images.githubusercontent.com/15825376/32587288-8c90540c-c542-11e7-805d-86cbd2081b85.png)

Thanks

**Comment by jincod** [comment]
Hi @kodelapan 

I've reviewed your app. It doesn't have `HomeController\Index` method or default route configuration. But if you try to go to https://coffeebali.herokuapp.com/article/1/1 (https://github.com/kodelapan/coffeemaker/blob/d5d0b39bd88ee66e7580cd0e1920ed7c4fc88057/coffeemaker.api/coffeemaker.api/Controllers/ArticleController.cs#L42) you get error. You should check logs.

**Comment by kodelapan** [comment]
@jincod thanks for helping, now issue resolved. When it will update the buildpack to asp.net core 2.0.3, since my issue caused by asynchronous issue on asp.net core 2.0.0

**Comment by jincod** [comment]
@kodelapan [updated .NET Core SDK to 2.0.2](https://github.com/jincod/dotnetcore-buildpack/commit/f757b31575efc8b3a81bde847a07567f0eb528a3)
