### ISSUE TITLE
Error while running migrations with "heroku run dotnet ef database update"

### ISSUE THREAD

**Issue by welkie** [jincod/dotnetcore-buildpack#33]
I used this buildpack to deploy to a Heroku app, and since it's a new deployment, I expected that I would need to run all the migrations to get the database ready for the app to run. Since I would run `dotnet ef database update` locally to do this, I figured I would `heroku run dotnet ef database update` to run this remotely. I have used Heroku before for Rails and I remember being able to do all the rake tasks by prepending them with `heroku run`.

When I run this though, it takes a long time to do something with the local package cache and then it displays an error message:

```
> heroku run dotnet ef database update
Running dotnet ef database update on ⬢ property-app-back-end... up, run.5524 (Free)

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 8288 ms
Expanding 100% 17908 ms
Version for package `Microsoft.EntityFrameworkCore.Tools.DotNet` could not be resolved.
```

Any idea what might be causing this?

**Comment by jincod** [comment]
Hi @welkie 

Thank you for report. 

Are `csproj file` which contains EF tools package locate at root of folder?

**Comment by welkie** [comment]
Thanks for looking at this with me. Yes, the `csproj` file is at the root of the project. It includes the following packages:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" PrivateAssets="All" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>
```

**Comment by welkie** [comment]
I wanted to come back and provide more context.

I originally encountered this error when Heroku-izing an existing ASP.NET Core 2.0 web app that I made. It used PostgreSQL for its database already.

I wanted to do another test to see if I could find the root of this problem, so today I created a new ASP.NET Core 2.0 app (with the `mvc` template and `--auth individual` to trigger the creation of the DbContext class and start some models) and tried to use this buildpack to get it hosted on Heroku. It actually worked no problem. The buildpack made all needed changes to the environment variables to have the app listen on the port Heroku gave it for HTTP.

At that point, I decided to switch it from SQLite to PostgreSQL. I used the `dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL` to add the provider NuGet package. After running this command, my `.csproj` file included the following package references:

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" PrivateAssets="All" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.2" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.1" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />
  </ItemGroup>
```

My `Startup.cs` file included this code in the `ConfigureServices` method:

```csharp
services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlite(Configuration.GetConnectionString("DefaultConnection")));
```

So I changed that code to the following, to use PostgreSQL instead:

```csharp
services.AddEntityFrameworkNpgsql().AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(Configuration.GetConnectionString("DefaultConnection")));
```

After adding the Heroku Postgres add-on, I had to hook up the connection string through environment variables, but I noticed I couldn't just use the `DATABASE_URL` environment variable since it isn't in a form that Npgsql can use. So I split up the connection URL in it into multiple environment variables and used those in the code:

![environment variables](https://i.imgur.com/25RFc2f.png)

**Comment by welkie** [comment]
Another update: I looked into how to run migrations at runtime. I got it to work pretty well I think:

Basically, you can have ASP.NET Core manually retrieve an instance of your DbContext after all of your services have been wired up. Then, you can call a method to run pending migrations before the app finishes starting. This method is detailed here: https://stackoverflow.com/questions/45885019/asp-net-core-2-get-instance-of-db-context

I wrapped it in an environment variable that I called `AUTO_MIGRATE` so that I could keep control over whether this happens at app startup. I ended up having the extension method:

```csharp
public static class IWebHostExtensions
{
    public static IWebHost MigrateDatabase(this IWebHost webHost)
    {
        // Manually run any outstanding migrations if configured to do so
        var envAutoMigrate = Environment.GetEnvironmentVariable("AUTO_MIGRATE");
        if (envAutoMigrate != null && envAutoMigrate == "true")
        {
           Console.WriteLine("*** AUTO MIGRATE ***");

           var serviceScopeFactory = (IServiceScopeFactory)webHost.Services.GetService(typeof(IServiceScopeFactory));

        using (var scope = serviceScopeFactory.CreateScope())
        {
            var services = scope.ServiceProvider;
            var dbContext = services.GetRequiredService<ApplicationDbContext>();

            dbContext.Database.Migrate();
          }
        }

        return webHost;
    }
}
```

And I just called it before `Run()` in my `Main` method:

```csharp
public static void Main(string[] args)
{
    BuildWebHost(args)
        .MigrateDatabase()
        .Run();
}
```

**Comment by nbarbettini** [comment]
@welkie Just to double-check, are you doing any seeding of the database in `Startup`? This used to be the right pattern in 1.1, but it's outdated as of 2.0:
https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.1#move-database-initialization-code
https://stackoverflow.com/questions/45148389/how-to-seed-in-entity-framework-core-2

I know it can cause some weird errors, although I don't know if it causes this specific error.

**Comment by welkie** [comment]
No seeding in `Startup`. All start up time database work done in `Program`. :)

**Comment by jincod** [comment]
Hi @welkie,

Sorry for late answer. Thank you so much for you researching!

Does it work for you? Can I close issue?

**Comment by welkie** [comment]
@jincod I'll be testing this buildback again this week or this weekend with 2.1. I'll let you know if I experience this issue running migrations on remote again.

**Comment by welkie** [comment]
@jincod Unfortunately, I'm still having issues with this. The error message seems to be different this time:

```
PS C:\Users\mattw\AspNetHerokuTest> heroku run dotnet ef database update
Running dotnet ef database update on ⬢ asp-net-heroku-test-21... up, run.8697 (Free)

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't in
clude command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telem
etry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

Configuring...
--------------
A command is running to populate your local package cache to improve restore speed and enable offline access. This comma
nd takes up to one minute to complete and only runs once.
Decompressing 100% 8328 ms
Expanding 100% 20737 ms

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other
platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/build_935fe4a28a4ea47a35ac9d8cd0007325/obj
/project.assets.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileO
ptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 buffe
rSize)
   at System.IO.File.OpenText(String path)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Could not find a part of the path '/tmp/build_935fe4a28a4ea47a35ac9d8cd0007325/obj/project.assets.json'.
```

**Comment by jincod** [comment]
Hi @welkie,

Right, `heroku run dotnet ef database update` doesn't work after application has published.

I suggest to add target to `csproj` file (https://github.com/jincod/AspNetHerokuTest/blob/9a38aae85790d7f11755e41e9844da606981758e/AspNetHerokuTest.csproj#L13-L15):

```
  <Target Name="PrePublishTarget" AfterTargets="Publish">
    <Exec Command="dotnet ef database update" />
  </Target>
```

Also I had to add some options to connection string
```
sslmode=Prefer;Trust Server Certificate=true
```
https://github.com/jincod/AspNetHerokuTest/commit/9a38aae85790d7f11755e41e9844da606981758e

> Source code: https://gitlab.com/mattwelke/AspNetCorePostgresHeroku

Fixed project here https://github.com/jincod/AspNetHerokuTest

Let me know please, if it works for you

**Comment by welkie** [comment]
@jincod Your solution makes sense. It looks like a way to do what I described earlier in this thread (run migrations automatically as the deploy is done or app starts up) more elegantly.

However, after I made the changes you made (adding the `Target` to the `csproj` file and adding the options to the PostgreSQL connection string) it didn't work for me. It's a new error for me:

```
remote:   info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
remote:         Entity Framework Core 2.1.0-rtm-30799 initialized 'ApplicationDbContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
remote:   System.Net.Sockets.SocketException (111): Connection refused
remote:      at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout) in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 703
remote:      at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 555
remote:      at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 414
remote:      at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:line 270
remote:   --- End of stack trace from previous location where exception was thrown ---
remote:      at Npgsql.NpgsqlConnection.Open() in C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:line 153
remote:      at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists() in C:\projects\EFCore.PG\src\EFCore.PG\Storage\Internal\NpgsqlDatabaseCreator.cs:line 216
remote:      at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
remote:      at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
remote:      at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
remote:      at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
remote:      at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
remote:   Connection refused
remote: /tmp/build_0309e9a3d97bfebe3add04cfd3da6766/AspNetHerokuTest.csproj(18,5): error MSB3073: The command "dotnet ef database update" exited with code 1.
remote:  !     Push rejected, failed to compile ASP.NET Core app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to asp-net-heroku-test-21.
remote:
To https://git.heroku.com/asp-net-heroku-test-21.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/asp-net-heroku-test-21.git'
```

**Comment by jincod** [comment]
@welkie could you please check that `ASPNETCORE_ENVIRONMENT` was set and not _Development_ ? Also are you able to connect to remote DB using PG Admin or psql?

**Comment by welkie** [comment]
@jincod That did the trick! I assumed it would be set to Production by default. The `ASPNETCORE_ENVIRONMENT` environment variable wasn't set at all. When I manually set it to `Production` and built my app again, it worked fine. I was able to create a user too, which means the EF Core code was able to run, meaning the migration must have automatically taken place.

Just for fun, yes, I'm able to access my Heroku Postgres database through PG Admin:

![](https://i.imgur.com/nRjXRY8.png)

Interestingly enough, I was wrong about not getting complete access on the free tier. I can see my tables too:

![](https://i.imgur.com/xBKgi9g.png)
![](https://i.imgur.com/Fep6C7X.png)

**Comment by jincod** [comment]
Hi @welkie,

> The ASPNETCORE_ENVIRONMENT environment variable wasn't set at all. When I manually set it to Production and built my app again, it worked fine.

By default `ASPNETCORE_ENVIRONMENT` is _Production_, but Visual Studio adds this file https://gitlab.com/mattwelke/AspNetCorePostgresHeroku/blob/master/Properties/launchSettings.json

Created issue for updating README https://github.com/jincod/dotnetcore-buildpack/issues/46

Thank you!

**Comment by welkie** [comment]
@jincod Ahh that makes sense. In my case, it was the .NET Core CLI that automatically created that file. Thanks for your patience helping me with this. It's clear I need to understand the tools more.

**Comment by luizs81** [comment]
@welkie 
Are you aware that the Postgres connection string (host, user, password) might change without previous notice?
https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku

> Do not copy and paste database credentials to a separate environment or into your application’s code. The database URL is managed by Heroku and will change under some circumstances such as:
> 
> - User initiated database credential rotations using heroku pg:credentials:rotate.
> - Catastrophic hardware failure leading to Heroku Postgres staff recovering your database on new hardware.
> - Automated failover events on HA enabled plans.

I haven't tested yet, but I believe you should get the `DATABASE_URL` from the environment and then extract the values you need in order to build the connection string in a format that Npgsql accepts.

**Comment by welkie** [comment]
@luizs81 Thanks for bringing that up. I never considered it when I wrote my comment on Apr 15. I've since changed my approach to be more dynamic. I came up with an algorithm to parse the Heroku-style connection URL to a connection string that Npgsql can use. I'm glad you brought it up because anyone following my old comment may have had some issues in the future. :+1: 

Here is my new approach:

```csharp
// Heroku provides PostgreSQL connection URL via env variable
var connUrl = Environment.GetEnvironmentVariable("DATABASE_URL");

// Parse connection URL to connection string for Npgsql
connUrl = connUrl.Replace("postgres://", string.Empty);

var pgUserPass = connUrl.Split("@")[0];
var pgHostPortDb = connUrl.Split("@")[1];
var pgHostPort = pgHostPortDb.Split("/")[0];

var pgDb = pgHostPortDb.Split("/")[1];
var pgUser = pgUserPass.Split(":")[0];
var pgPass = pgUserPass.Split(":")[1];
var pgHost = pgHostPort.Split(":")[0];
var pgPort = pgHostPort.Split(":")[1];

connStr = $"Server={pgHost};Port={pgPort};User Id={pgUser};Password={pgPass};Database={pgDb}";
```

**Comment by jincod** [comment]
@vohoanvu 
`IWebHost ` now `IHostBuilder`
check this article https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#configuration
