### ISSUE TITLE
How to build/deploy an app from a subfolder of a .sln project structure

### ISSUE THREAD

**Issue by dstj** [jincod/dotnetcore-buildpack#38]
Hi,

I have successfully deployed a dotnet core test web app with the `.csproj` at the root of my git folder. But now, for my real app, I have this "complex" folder structure for my .sln and git repo:

```
/
|---MySolution.sln
|---WebProject/
|    |---WebProject.csproj
|    |---... other web project files
|---WebProject.Tests/
|    |---... C# unit test classes
|---CoreAssembly/
|    |---... core assembly classes
|---CoreAssembly.Tests/
|    |---... core assembly C# tests classes
```

How do I use this dotnetcore-buildpack to deploy my app to hekoku? What should I push? How do I tell it that the `WebProject/` folder is right folder to run?

Thanks!

**Comment by jincod** [comment]
Hi @dstj 

I believe it should work. 

Just to confirm, where is located `Startup.cs` file, I suppose near `WebProject.csproj`. Isn't?

For example, you can check structure at https://github.com/jincod/AspNet5DemoApp/tree/master/src/AspNetCoreDemoApp

**Comment by dstj** [comment]
@jincod, yes, correct, the `Startup.cs` would be in the `WebProject` folder.

So I just push everything, tests included to Heroku? Thanks for answering. If I have some spare time today, I'll make a PR to improve the README.md for newbies like me :)

**Comment by jincod** [comment]
Thank you! It would be great!
