### ISSUE TITLE
No executable found matching command "dotnet-./build_*.dll"

### ISSUE THREAD

**Issue by AlexByte** [jincod/dotnetcore-buildpack#4]
I get this error when I run the app.

**Comment by jincod** [comment]
Hi @AlexByte 

I think You have same problem [issue-2](https://github.com/jincod/dotnetcore-buildpack/issues/2#issuecomment-306426217). To fix it, move your project into Folder with same name as csproj file. Example `Web\Web.csproj`

**Comment by AlexByte** [comment]
Thanks, it helped. Why in this buildpack it was not required?
https://github.com/noliar/dotnet-buildpack

**Comment by jincod** [comment]
@AlexByte thank you for feedback.

It's "by design"😀. Maybe I will update readme or change this behavior.

Can I close issue?

**Comment by AlexByte** [comment]
Yes, you can.

**Comment by jincod** [comment]
Hi @AlexByte 

I've updated buildpack to support building project located at root https://github.com/jincod/dotnetcore-buildpack/commit/71119cddd35f489fe365adc4177c482ff6ea82cd
