### ISSUE TITLE
Allow use of alternative package sources (myget)

### ISSUE THREAD

**Issue by xt449** [jincod/dotnetcore-buildpack#48]
Please allow use of alternative package sources like myget.

I'm not familiar with buildpacks or i would add this capability, so if you point me in the right direction I could make a fork instead.

**Comment by jincod** [comment]
Hi @xt449 

It should work by default. Just add _Nuget.config_ to root project directory ([Example](https://docs.myget.org/docs/how-to/nuget-configuration-inheritance#Example_1_a_project-specific_configuration)) or use _RestoreAdditionalProjectSources_ in csproj file [(Source)](https://github.com/aspnet/Home/wiki/.NET-Core-2.1.1-Early-Access-Downloads#what-about-the-packages)

Example:
```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.1</TargetFramework>
  <RestoreAdditionalProjectSources>
      https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180605-09/final/index.json
  </RestoreAdditionalProjectSources>
</PropertyGroup>
```

**Comment by xt449** [comment]
Alright, thanks! Looks like adding RestoreAdditionalProjectSources and a custom nuget.config works
