### ISSUE TITLE
Upgrade to support ASP.NET Core 2.1.1

### ISSUE THREAD

**Issue by welkie** [jincod/dotnetcore-buildpack#50]
I noticed when trying to use the buildpack with 2.1.1 that it exits with error code 150 when deploying. Going back to 2.1.0 of the NuGet package fixed this. I think the buildpack needs to be updated.

**Comment by jincod** [comment]
Hi @welkie 

I've updated SDK to 2.1.301. Could you please test for your case?

**Comment by VitaliiIsaenko** [comment]
After update another problem appears. With previous version - 2.1.0. When tried to deploy app as usual I got an error: <br/>
```
/tmp/build_1ee73317524a24c35a7890a21f117f93/easyLearning-server.csproj : error NU1605: Detected package downgrade: Microsoft.EntityFrameworkCore.Design from 2.1.1 to 2.1.0. Reference the package directly from the project to select a different version. 
/tmp/build_1ee73317524a24c35a7890a21f117f93/easyLearning-server.csproj : error NU1605:  easyLearning-server -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.EntityFrameworkCore.Design (>= 2.1.1 && < 2.2.0) 
/tmp/build_1ee73317524a24c35a7890a21f117f93/easyLearning-server.csproj : error NU1605:  easyLearning-server -> Microsoft.EntityFrameworkCore.Design (>= 2.1.0)
  Generating MSBuild file /tmp/build_1ee73317524a24c35a7890a21f117f93/obj/easyLearning-server.csproj.nuget.g.props.
  Generating MSBuild file /tmp/build_1ee73317524a24c35a7890a21f117f93/obj/easyLearning-server.csproj.nuget.g.targets.
  Restore failed in 6.22 sec for /tmp/build_1ee73317524a24c35a7890a21f117f93/easyLearning-server.csproj.
 !     Push rejected, failed to compile ASP.NET Core app.
 !     Push failed
```
Will it be possible to use this buildpack without updating the SDK?

**Comment by VitaliiIsaenko** [comment]
Unfortunately, I faced a problem with deploying now that I didn't have before. I suppose it is connected to this issue. I use SDK 2.1.300 and use latest stable .NET core for buildpack to deploy. I have this error that I didn't have before:
```/tmp/build_1ee73317524a24c35a7890a21f117f93/easyLearning-server.csproj : error NU1605: Detected package downgrade: Microsoft.EntityFrameworkCore.Design from 2.1.1 to 2.1.0. Reference the package directly from the project to select a different version. 
/tmp/build_1ee73317524a24c35a7890a21f117f93/easyLearning-server.csproj : error NU1605:  easyLearning-server -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.EntityFrameworkCore.Design (>= 2.1.1 && < 2.2.0) 
/tmp/build_1ee73317524a24c35a7890a21f117f93/easyLearning-server.csproj : error NU1605:  easyLearning-server -> Microsoft.EntityFrameworkCore.Design (>= 2.1.0)
  Generating MSBuild file /tmp/build_1ee73317524a24c35a7890a21f117f93/obj/easyLearning-server.csproj.nuget.g.props.
  Generating MSBuild file /tmp/build_1ee73317524a24c35a7890a21f117f93/obj/easyLearning-server.csproj.nuget.g.targets.
  Restore failed in 6.22 sec for /tmp/build_1ee73317524a24c35a7890a21f117f93/easyLearning-server.csproj.
 !     Push rejected, failed to compile ASP.NET Core app.
 !     Push failed
```
Is it possible to fix it somehow?

**Comment by welkie** [comment]
It looks like we might be in a situation where we must use a build pack associated with only the version of ASP.NET Core we're using. Is that true?

**Comment by welkie** [comment]
@jincod I just tried building my app again without changing from 2.1.0 to 2.1.1. It built fine. When I attempt to run the command to add the buildpack again, I get:

```
$ heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack
 ▸    The buildpack https://github.com/jincod/dotnetcore-buildpack is already set on your app.
```

So it looks like my 2.1.0 project is building with the latest buildpack. Unless there's some sort of buildpack caching going on?

**Comment by friism** [comment]
Maybe try blowing away the build cache: https://github.com/heroku/heroku-repo#purge-cache

**Comment by welkie** [comment]
@friism I ended up resetting the build cache while playing around with some things. It looks like a ```dotnet restore --no-cache``` did the trick. It caused the Heroku build messages to say it was building the `2.1.1` versions instead of just a message saying it restored packages from a cache.

While I was playing around with this I made a fresh 2.1.0 app and tried to use the latest buildpack. It built for me and deployed successfully. @VitaliiIsaenko Maybe try the ```dotnet restore --no-cache``` command before you git add, git commit, and push to heroku master?

**Comment by jincod** [comment]
Hi @VitaliiIsaenko

I've added tag for 2.1.300. You can set using CLI:
```
heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack#v2.1.300
```

**P.S.**: According to the article https://devcenter.heroku.com/articles/buildpacks#buildpack-references use can use specific commit `https://github.com/jincod/dotnetcore-buildpack#64cf9ce` ([source](https://github.com/jincod/dotnetcore-buildpack/commit/64cf9ce)).

**Comment by jincod** [comment]
Also try to specify package version:
```diff
-<PackageReference Include="Microsoft.AspNetCore.App" />
+<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0" />
```

More info https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#rules-for-projects-targeting-the-shared-runtime

**Comment by VitaliiIsaenko** [comment]
@welkie unfortunately, restoring with --no-cache option didn't solve the problem. 
@jincod thank you, it worked for me! Strange that version 21.300 didn't require it.
Really nice that you have such a supportive community here. .NET rocks!
