### ISSUE TITLE
Specify project

### ISSUE THREAD

**Issue by YauhenIhnatsyeu** [jincod/dotnetcore-buildpack#52]
How to specify project, which will be launched?
For example, I want to start "FS.Web" project.

![image](https://user-images.githubusercontent.com/36185282/43207653-372fc67c-9031-11e8-89f1-9ea8eed48031.png)

**Comment by jincod** [comment]
Hi @YauhenIhnatsyeu 

You don't need to specify anything. Try to check this issue https://github.com/jincod/dotnetcore-buildpack/issues/38
