### ISSUE TITLE
Update to SDK 2.1.400

### ISSUE THREAD

**Issue by dstj** [jincod/dotnetcore-buildpack#55]
Hi @jincod, I noticed that you have a branch `develop` with the upgrade to the 2.1.400 SDK (I tried it, it works fine), do you know when you'll push it to master?

**Comment by jincod** [comment]
Hi @dstj 

I've merged this to master

**Comment by dstj** [comment]
Thanks @jincod, I just noticed that 2.1.401 come out...

Here's the link to it:
https://download.microsoft.com/download/E/8/A/E8AF2EE0-5DDA-4420-A395-D1A50EEFD83E/dotnet-sdk-2.1.401-linux-x64.tar.gz

**Comment by jincod** [comment]
Hi @dstj,

I've merged🙂
