### ISSUE TITLE
Remove Startup.cs file Requirement

### ISSUE THREAD

**Issue by xt449** [jincod/dotnetcore-buildpack#58]
I really have no idea what Startup.cs class does normally, except that VS generates it with web apps, but there is no reason the developer might not change the file name.

I'm not using a web dyno and my project is not a web application so I do not need the normally auto-generated Startup.cs file.

**Comment by welkie** [comment]
@jincod Microsoft documentation actually tells people that they decoupled it on purpose. The `Startup` class name is just a convention. There was a training video I watched on MSDN where Scott Hanselman talked about this with a co-presenter.

**Comment by welkie** [comment]
It might make more sense to only require the project be a .NET Core project, as opposed to an ASP.NET Core project, to use this buildpack, since a .NET Core web app need not be made with ASP.NET Core. Alternatives include Nancy.

**Comment by xt449** [comment]
I think it may already only require .NET Core as my project file says Sdk=Microsoft.NET.Sdk and the target framework is netcoreapp2.1 without any ASP package references

**Comment by welkie** [comment]
Sounds like the requirement for a `Startup.cs` file could be removed then. Searching for a project file with `Sdk=Microsoft.NET.Sdk` and/or the .NET Core targets should be enough. At the end of the day, the binary is executed and the rest of the details like which class has the entry point is abstracted away anyways.

**Comment by xt449** [comment]
I would make a PR for this but my internet is down from a storm I had last night.

**Comment by xt449** [comment]
Forgot about this for a bit, but I have a better idea that allows older projects to continue using Startup.cs to identify the project directory.
First look for a Startup.cs file and then for the more common Program.cs file.
