### ISSUE TITLE
Setting environments for Heroku pipelines

### ISSUE THREAD

**Issue by JayHelton** [jincod/dotnetcore-buildpack#59]
Hello, I was wondering if there was a way to set the dotnet environment based on the pipeline being used. I will be needing a staging environment as well as a production environment.

**Comment by jincod** [comment]
Hi @JayHelton,

I don't have any experience with pipelines, but you can try check https://github.com/heroku/salesforce-buildpack and https://github.com/wadewegner/salesforce-dx-pipeline-sample as example for pipelines.

**Comment by JayHelton** [comment]
@jincod thank you! I will attempt to implement this when I finish a feature I am on.

**Comment by jincod** [comment]
Hi @JayHelton,

Have you tried to implement this? If yes, could you please share your experience?

**Comment by JayHelton** [comment]
Unfortunately I have not gotten to the life cycle of the project where it's need. Side projects move too slowly. Theoretically, we can probably change the dotnet command to run configurations based off a heroku env variable. I've done something similar with an after install NPM script. Sorry to disappoint!

**Comment by AlexandreBonfim** [comment]
Hi @jincod I'm trying to push my web api in dotnetcore to Heroku using GIT CI/CD. Everything is working, but, I need to change the environment on the pipeline (staging/ production). So I'm using export ASPNETCORE_ENVIRONMENT="Staging" to update database in each environment and its working.

Now, after the push, the API only is working on Production. I tried to follow the links that you gave to @JayHelton but they didnt help in my situation. Any advice?

Follow my yml file... Thanks!

# global image for docker
image: microsoft/dotnet:2.2-sdk

# Restoring and getting all dependencies for solution
before_script: 
  - cd unicorn-api
  - dotnet restore --packages ./.nuget/  

# Jobs that will run on the pipeline
stages:
  - build
  - test
  # - chatops
  - deploy

# variables:
  # clean up later on
  # test: "Example.Test"
  # call it with $test

build:staging:
  stage: build
  script:     
    # update database   
    - export ASPNETCORE_ENVIRONMENT="Staging"
    - dotnet ef database update 
    - echo "Staging dataBase Updated" 
    # Reduce each job to only one statement: dotnet build/test with –no-restore flag, as we restore packages with before_script
    - dotnet build #-c Release #-o ../artifacts/staging --no-restore
  #artifacts:
   # name: "unicorn-buld"
    #paths:
     # - artifacts/staging

build:production:
  stage: build
  script:
    - export ASPNETCORE_ENVIRONMENT="Production"
    - dotnet ef database update 
    - echo "Production dataBase Updated"
    - dotnet build #-c Release #-o ../artifacts/production --no-restore  
  #artifacts:
   # name: "unicorn-publish"
    #paths:
     # - artifacts/production

test:
  stage: test
  dependencies:
    - build:staging
  script:
    - cd ..
    - cd Tests
    - dotnet test --no-restore   

# message on slack - testing
# hello-world:
#   stage: chatops
#   only: [chat]
#   script:
#     - echo "Hello World. Tests passed!"

deploy_staging:
  stage: deploy 
  environment:
    name: staging
    url: https://xxxx.herokuapp.com/
  only:
    - master
  dependencies:
    - build:staging
  script: 
    - cd ..
    - cd unicorn-api
    # run docker here ---> still testing !!!
    # - docker build -t netcore-project
      
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/xxx.git
    - git push heroku HEAD:master
    - echo "Deployed to staging server"
 

deploy_production:
  stage: deploy
  environment:
    name: production
    url: https://xxx.com/
  # Need to be started from user
  when: manual
  only:
    - master
  dependencies:
    - build:production
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/xxxx
    - git push heroku HEAD:master
    - echo "Deployed to production server"

**Comment by AlexandreBonfim** [comment]
Hi guys, found solution:

 - heroku config:set ASPNETCORE_ENVIRONMENT="Staging" -a <APP_NAME>

Hope it helps others and doesn't spend a day trying to find a solution 💯
