### ISSUE TITLE
Specify csproj?

### ISSUE THREAD

**Issue by KerryRitter** [jincod/dotnetcore-buildpack#6]
I have a multi-project solution. How do I set the correct project to start? I created a .deployment file with the following:

```
[config]
project = MyProjectFolder
```

**Comment by jincod** [comment]
Hi @KerryRitter 

Thank you for interest to this buildpack

Do you have many Web projects in this solution? If only one (and one Startup.cs), then no problem.

```bash
PROJECT_FILE=$(find $(dirname $(find ${BUILD_DIR} -maxdepth 5 -iname Startup.cs | head -1)) -maxdepth 1 -iname '*.csproj' | head -1)
PROJECT_NAME=$(basename ${PROJECT_FILE%.*})
```

This script will find correct csproj file. 

Do you still have problem?

**Comment by KerryRitterWaa** [comment]
Actually I found that my problem was that it was trying to publish a class library, and there were some other issues related to that. This can be closed.

**Comment by KerryRitter** [comment]
Actually I found that my problem was that it was trying to publish a class library, and there were some other issues related to that. This can be closed.
