### ISSUE TITLE
Exception during Bitmap type initialization

### ISSUE THREAD

**Issue by xt449** [jincod/dotnetcore-buildpack#62]
Reproduce with anything like this
```csharp
new System.Drawing.Bitmap(x, y);
```
which will throw a TypeInitializationException:
`
The type initializer for 'Gdip' threw an exception.
`

The only reason I can see for this is that the initializer for a Bitmap object may be trying to creating a temporary file, which Heroku does not like.
**I thought I would put this hear to confirm what I was thinking and maybe get some feedback from people familiar with Heroku.**

**Comment by jincod** [comment]
Hi @xt449,

Could you please check this article https://www.hanselman.com/blog/HowDoYouUseSystemDrawingInNETCore.aspx?

**Comment by xt449** [comment]
I have read the article. Nothing new to me
