### ISSUE TITLE
Can this buildpack support a multiple project structure?

### ISSUE THREAD

**Issue by seguidor777** [jincod/dotnetcore-buildpack#63]
Hello, I have been trying this buildpack with an application consisting of multiple .csproj files
as following:

- MyApp
  - MyApp.Business/MyApp.Business.csproj
  - MyApp.Data/MyApp.Data.csproj
  - MyApp.Entity/MyApp.Entity.csproj
  - MyApp.Framework/MyApp.Framework.csproj
  - MyApp.WEB/MyApp.WEB.csproj

The main project here is is **MyApp.WEB** which links all other projects, this in turn contains an AngularJS application in MyApp.WEB/ClientApp which requires NPM to be installed.
Could you please tell me if it is possible to build multiple projects with any configuration, for example a .deployment file with all the projects?

**Comment by jincod** [comment]
Hi @seguidor777,

You can find more info here https://github.com/jincod/dotnetcore-buildpack/issues/51 and https://github.com/jincod/dotnetcore-buildpack/issues/38

**Comment by seguidor777** [comment]
Thanks for your reply @jincod!

According to issue #38, Does it mean that I have to place my **MyApp.WEB.csproj** file into the root directory?

**Comment by welkie** [comment]
@seguidor777 I have a repo that has a solution file at the root directory and two projects (one in `src/ProjectName` and one in `test/ProjectName`) and the buildpack was able to pick up on the fact that the main project to run was in the `src` directory.

**Comment by seguidor777** [comment]
Oh yeah! It seems that the main project is automatically detected by its Startup.cs file.
Now I am having trouble with the directory name, because when publishing, it tries to open a directory called WebAPI but it is not being generated.

`2018-09-11T19:13:56.397898+00:00 heroku[web.1]: Starting process with command `cd /app/heroku_output/WebAPI && dotnet ./MyApp.dll --server.urls http://+:41303 ${CORE_ENVIRONMENT}`
2018-09-11T19:13:58.716727+00:00 heroku[web.1]: Process exited with status 1
2018-09-11T19:13:58.734236+00:00 heroku[web.1]: State changed from starting to crashed
2018-09-11T19:13:58.665563+00:00 app[web.1]: bash: line 0: cd: /app/heroku_output/WebAPI: No such file or directory
`

**Comment by seguidor777** [comment]
I apologize, I have a wrong Procfile with that directory

**Comment by seguidor777** [comment]
Now I am facing another problem with the executable, because it is not being found

2018-09-11T19:25:11.805194+00:00 heroku[web.1]: Starting process with command `cd /app/heroku_output && ./MyApp.WEB`
2018-09-11T19:25:13.107939+00:00 app[web.1]: bash: **./MyApp.WEB: No such file or directory**
2018-09-11T19:25:13.149187+00:00 heroku[web.1]: Process exited with status 127
2018-09-11T19:25:13.177619+00:00 heroku[web.1]: State changed from starting to crashed

Any idea of what is happening?

**Comment by seguidor777** [comment]
Finally I could deploy my application with a custom Procfile, since the name of the executable is not the same of the project name. No more issues on my end

**Comment by welkie** [comment]
@seguidor777 Why is the name of the executable in your project not the same name as its project?

**Comment by seguidor777** [comment]
As I can see, the compiler script tries to run an executable with the same name of the root directory, but in this special case another developer named the main project with a different name than "MyApp".
Thanks for your help man!

**Comment by welkie** [comment]
@seguidor777  Ahh I see. That makes more sense. Glad you got it resolved. :)
