### ISSUE TITLE
Support Dotnet Core 2.2

### ISSUE THREAD

**Issue by knyzorg** [jincod/dotnetcore-buildpack#67]
Dotnet Core 2.2 has been available for some time now and should be supported.

**Comment by jincod** [comment]
Hi @knyzorg,

You can already use .NET Core 2.2 preview 3 by this link `https://github.com/jincod/dotnetcore-buildpack#preview`

or using CLI
```
heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack#preview
```
