### ISSUE TITLE
Support for solution with multiple ASP.NET Core projects

### ISSUE THREAD

**Issue by bolorundurowb** [jincod/dotnetcore-buildpack#68]
I have a solution with two Web API projects and one shared Library containing migrations. How can specify which project I want built and deployed on the dyno

**Comment by bolorundurowb** [comment]
Thanks @jincod. #23 really helped. Do you think you can include that in the README? It would really help others.

**Comment by bolorundurowb** [comment]
Hi @jincod I have noticed that specifying the `PROJECT_NAME` environment variable is a hit or miss situation. The first deployment after setting the environment variable works well but subsequent ones default to picking the first project alphabetically

**Comment by jincod** [comment]
Hi @bolorundurowb,

Could you provide more details, logs or maybe can you share project on github?

**Comment by bolorundurowb** [comment]
@jincod sorry for not responding earlier, I got it fixed by specifying both the `PROJECT_NAME` and `PROJECT_FILE` in the environment variables
