### ISSUE TITLE
The library 'libhostpolicy.so' required to execute the application was not found in '/app/heroku_output'.

### ISSUE THREAD

**Issue by KerryRitterWaa** [jincod/dotnetcore-buildpack#7]
I am deploying https://github.com/jincod/dotnetcore-buildpack#v1.0.4 to heroku-16 and I'm getting the following error:

```
2017-08-14T20:15:27.264133+00:00 heroku[web.1]: Starting process with command `cd /app/heroku_output && ASPNETCORE_URLS='http://+:24210' dotnet "./MyApp.dll" --server.urls http://+:24210`
2017-08-14T20:15:29.668097+00:00 app[web.1]: A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/heroku_output'.
```

Any suggestions?

**Comment by KerryRitterWaa** [comment]
I had to fork and add a call specifically to add the ubuntu 16 runtime. see: https://github.com/KerryRitterWaa/dotnetcore-buildpack/blob/master/bin/compile

Do you want to add this change to the v1.0.4 tag?

**Comment by jincod** [comment]
Hi @KerryRitterWaa 

Thank you for your research.

I'll check it and notify you when I update buildpack

**Comment by jincod** [comment]
Hi @KerryRitterWaa 

I have added this change (https://github.com/jincod/dotnetcore-buildpack/commit/50f4474f0271f1698ce3ac5bd041b21f863dc5a0) and have updated buildpack (both master and v1.0.4). Could you please test it?

**Comment by rvs76** [comment]
Hi,

I have the same error :'-(

2017-09-05T07:55:35.988468+00:00 app[web.1]: A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/parcours-client/bin/Release/netcoreapp1.1/linux-x64'.

**Comment by jincod** [comment]
Hi @rvs76 

Do you use the same version of buildpack https://github.com/jincod/dotnetcore-buildpack#v1.0.4?

**Comment by rvs76** [comment]
Yes, i use  this buildpack.

**Comment by jincod** [comment]
@rvs76 could you share your project on github to reproduce this issue?

**Comment by rvs76** [comment]
Not publicly, private only.

**Comment by rvs76** [comment]
By email ?

**Comment by jincod** [comment]
@rvs76 vadim.abdrashitov@gmail.com

**Comment by rvs76** [comment]
Sent.
You can delete your message.

**Comment by rvs76** [comment]
mx.google.com a généré cette erreur :
This message was blocked because its content presents a potential security issue. Please visit https://support.google.com/mail/?p=BlockedMessage to review our message content and attachment content guidelines. p14si26694pli.693 - gsmtp

**Comment by truccomarcos** [comment]
Hi,

Im getting the same error when using https://github.com/jincod/dotnetcore-buildpack#v1.0.4

"A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/heroku_output'."

It did not happen before, latest deploy was 6 days ago and it seemed to work just fine, so it seems kinda weird that it just started happening. Is it possible that a recent update might have broken it?

**Comment by jincod** [comment]
@rvs76 could you please resend invite to `vadim.abdrashitov@gmail.com`

@truccomarcos could you share your project or share access to heroku project?

**Comment by rvs76** [comment]
@jincod : Invite ???
Resend project ?

**Comment by jincod** [comment]
@rvs76 add me to heroku project collaborators if you can

**Comment by rvs76** [comment]
@jincod : I can but I think my boss will not agree ;-)

**Comment by jincod** [comment]
@rvs76 ok, understood:)

Maybe @truccomarcos can share project to reproduce this issue.

**Comment by truccomarcos** [comment]
I really can't share the project since I dont own it.
I could "fix" the build issue by forking the buildpack and un-doing the last commit there.
https://github.com/truccomarcos/dotnetcore-buildpack/tree/v1.0.4

**Comment by rvs76** [comment]
Same error with truccomarcos solution !

**Comment by SumeetGohil** [comment]
I am facing same issue :(

A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/heroku_output/'.

**Comment by jincod** [comment]
Hi all

Could you share your *csproj* files (Web application) to find the difference?

**Comment by truccomarcos** [comment]
Hi,
I apologize for not being able to share the code itself.
Here's how the csproj looks:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <UserSecretsId>ProjectName</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.2"/>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3"/>
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2"/>
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.2"/>
    <PackageReference Include="Npgsql" Version="3.2.3"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="1.1.0"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0"/>
    <PackageReference Include="RestSharp.NetCore" Version="105.2.3"/>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0"/>
    <PackageReference Include="SmartFormat.Net" Version="2.1.0.2"/>
    <PackageReference Include="CsvHelper" Version="2.16.3"/>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0"/>
  </ItemGroup>
</Project>`

**Comment by jincod** [comment]
Hi all

Is this issue connected with .net core 1.0 only? Right?

**Comment by AlexByte** [comment]
Why was to break the buildpack? 😞

**Comment by jincod** [comment]
Hi @AlexByte 

Thank for you report. I checked you fixes (https://github.com/truccomarcos/dotnetcore-buildpack/commit/505194017dc85317362d7f3d2cc35e9ee8707248).

People have problems with `--runtime linux-x64` other people have problem with `--runtime ubuntu.16.04-x64` as well. 

We haven't found solution yet.

**Comment by AlexByte** [comment]
It's fixes of truccomarcos https://github.com/jincod/dotnetcore-buildpack/issues/7#issuecomment-327625468

**Comment by jincod** [comment]
I've reverted runtime option for `v1.0.4`. Now `--runtime ubuntu.16.04-x64`.

Could someone test it?

**Comment by AlexByte** [comment]
Now it works, of course.

**Comment by jincod** [comment]
Thx all😄

If error will reproduce again, please open this issue
