### ISSUE TITLE
HttpSys support?

### ISSUE THREAD

**Issue by itjstagame** [jincod/dotnetcore-buildpack#72]
I am trying to use Http.sys to get NTLM authentication as described here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2#enable-windows-authentication-with-httpsys

I am getting this during build:
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Server.HttpSys.HttpApi' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'httpapi.dll' or one of its dependencies.

It does say it isn't supported on Nano Server version 1709 or later and other requirements.  I can't tell if it's an issue with your buildpack or not since I see you basically just pull down requirements but I'm not sure why this requirement is not being pulled in.

**Comment by friism** [comment]
> HTTP.sys is a web server for ASP.NET Core that only runs on Windows.

 - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.2

Heroku is built on Linux, so I don't think HTTP.sys is going to work
