### ISSUE TITLE
Some static files are not deployed.

### ISSUE THREAD

**Issue by Yanchi4425** [jincod/dotnetcore-buildpack#74]
Hello.
I deployed the application using this build pack, but some static files are not expanded.
(In the wwwroot dir.)

<img width="800" alt="issue" src="https://user-images.githubusercontent.com/5096738/52560023-617be080-2e3a-11e9-851c-858bc0620be3.png">

I am using this gitignore file and it has no problem.
[https://www.gitignore.io/api/aspnetcore](https://www.gitignore.io/api/aspnetcore)

I tried deploying it several times and made new apps.
But, only these two files can not be read.
However, other files can be read without problems.

Next, I looked up in the directory of heroku. 

`heroku run ls -l <My-App-Dir>/wwwroot/js`
 -> -rw------- 1 u43728 dyno 1293 Feb 11 11:19 core.js

And the file in the heroku_output directory.
`heroku run ls -l heroku_output/wwwroot/js`
 -> ls: cannot access 'heroku_output/wwwroot/js': No such file or directory

It appears in the repository, but it seems that the file is not expanded.

I manually overwrote the wwwroot directory.
`heroku run "cp -f -r <My-App-Dir>/wwwroot heroku_output/wwwroot"`
And restart  My App.
`heroku restert`

But,  it did not solve it.

I do not know whether there is a problem with the build pack or whether there is a problem with my environment.

Also, where is the wwwroot folder  this app hosting?

**Comment by jincod** [comment]
Hi @Yanchi4425,

Have you set `app.UseStaticFiles()` at your `Startup.cs`?

**Comment by Yanchi4425** [comment]
Hi @jincod ,
I was not particularly conscious, but it exists.
I'm using the application made with the `dotnet new mvc` command as it is.

```CSharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
        app.UseHsts();
    }

    app.UseHttpsRedirection();
    app.UseStaticFiles();
    app.UseCookiePolicy();

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
    });
}
```

I think that there is no problem because other static files are being loaded.
Also, when executing locally, all static files are loaded.

**Comment by jincod** [comment]
I suppose these files was generated and don't exists in repo.

Check this project https://github.com/jincod/AspNetCoreDemoApp/blob/5d1c589c958819beb98a7f9618a71ecf1562fc1d/src/AspNetCoreDemoApp/AspNetCoreDemoApp.csproj#L29 

Here I use "hack" to include static assets to publish

**Comment by Yanchi4425** [comment]
As I told you, I edited the csproj file.
My csproj file looked like this.
```xml
...
<ItemGroup>
    <Content Remove="wwwroot\js\core.js" />
    ...
</ItemGroup>
...
```

It seems that it was added during trial and error.
This was the cause....

Sorry and thank you for your time.

**Comment by tteguayco** [comment]
Hi,

Sorry for "necroposting", but I'm facing the same issue described here and I don't understand how to fix it. For every deploy I do to Heroku, any static file located under the folder `wwwroot` is found (404 errors on browser's console).

I've also added `app.UseStaticFiles()` to my `Startup.cs::Configure()`, but no success...

**Comment by jincod** [comment]
Hi @tteguayco,

Please create new issue and describe your problem.

- were files generated?
- are files exist at wwwroot after deployment?
