### ISSUE TITLE
netcore2.2 https authentication causes 400 error on heroku

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [jincod/dotnetcore-buildpack#78]
Hello, 

We are developing a netcore2.2 application on heroku, its on staging phase. We swiched to https protocol and after any successful login, we keep getting 400 errors on all requests. We suspect that it is related with non-ascii characters which are not being set on nginx server. 
I am not sure whether this is related with this buildpack but, someone gets the same issue in this following link: https://stackoverflow.com/a/53449963/1988124 

Is there any place in which we can add this code block to buildpack or is is related with heroku side? May I have your comments about the issue? 
@metinirden

**Comment by jincod** [comment]
Hi @oguzhankahyaoglu,

Here article how http routing work on Heroku https://devcenter.heroku.com/articles/http-routing

If you get problem after switching to https, check this issue https://github.com/jincod/dotnetcore-buildpack/issues/49

> Is there any place in which we can add this code block to buildpack or is is related with heroku side? 

Unfortunately, no, buildpack has other responsibilities.

Could you share Heroku routing logs?

**Comment by oguzhankahyaoglu** [comment]
Okay I see, we solved the problem with moving authentication tickets from cookie storage to Redis storage. The problem was about either invalid characters in cookie or cookie size limit. We have another web project within that solution which stores a smaller amount of authenticaiton data in cookie and it was working perfectly. After moving to redis, the problem is solved. Thanks.
