### ISSUE TITLE
Worker dynos in custom Procfile

### ISSUE THREAD

**Issue by darbio** [jincod/dotnetcore-buildpack#79]
Is there a way to specify the build pack to build other dynos specified in the Procfile? For my use case, I have my WebApi and then I have a console worker application. The build pack builds and runs the WebApi correctly, but the Console application never gets built.

**Comment by jincod** [comment]
Hi @darbio,

Unfortunately this buildpack doesn't support this case

**Comment by darbio** [comment]
Could it work by building the solution rather than a project? I will have a play around and see.

**Comment by darbio** [comment]
Looked into it. No joy - publish is not the same as build. Never mind! I've forked the build pack and changed it for my purposes. Thanks :+1:
