### ISSUE TITLE
Apply search logic change to v1.0.4

### ISSUE THREAD

**Issue by lppkarl** [jincod/dotnetcore-buildpack#8]
Hi @jincod, thanks again for the buildpack. I have noticed you have recently updated the search logic on getting the correct path for a dotnet project, but the code in v1.0.4 tag is not updated yet. 

I have tried to make a PR of it but it's not possible to make a PR from a tag. It would be great if you can update it for v1.0.4 users, thanks :)

**Comment by jincod** [comment]
Hi @lppkarl,

Thank you for your feedback.

I'll notify you when I update buildpack😀

**Comment by jincod** [comment]
Hi @lppkarl 

I've create branch v.1.0.4 with updated search logic. Could you please test it and confirm what everything is ok?

**Comment by lppkarl** [comment]
@jincod thanks! I will test it with the old 1.0.4 asp.net core spa project, i will tell you once i have completed the testing :)

**Comment by lppkarl** [comment]
@jincod the buildpack works perfectly on a 1.0.4 asp.net core spa without any change in folder structure :) The sample site is deployed here: https://dashboard.heroku.com/apps/afternoon-harbor-86717 . I am going to close this issue, thank you!

**Comment by jincod** [comment]
Hi @lppkarl 

Thank you for testing!
