### ISSUE TITLE
Successfully build but I get an error Application error when enable app.UseMvc

### ISSUE THREAD

**Issue by phat471996** [jincod/dotnetcore-buildpack#80]
Hi, I'm trying to build asp.net core 2.1 on heroku. It is ok if project is empty with index.html but when I create new controller and enable `app.UseMvc();` in Startup class I get an error Application error
![image](https://user-images.githubusercontent.com/22562250/55613517-0d93d500-57b5-11e9-9cfa-8d5e1a007635.png)
My project is an new project
https://github.com/phat471996/dotNetCore

**Comment by jincod** [comment]
@phat471996 could you please share Heroku logs of your app?

**Comment by jincod** [comment]
I checked your source code. First of all you missed `services.AddMvc();` at `ConfigureService`. I suppose, current version doesn't work locally as well.

**Comment by phat471996** [comment]
@jincod I'm sorry, I'm missed services.AddMvc(); at ConfigureService. Please close my issue. 
Thank you so much.
