### ISSUE TITLE
Specify ASPNETCORE_URLS via config var

### ISSUE THREAD

**Issue by kiran94** [jincod/dotnetcore-buildpack#81]
Hi, 

I can see from the following issue that you moved the init of ASPNETCORE_URLS variable to `profile/aspnetcore-defaults.sh`.

https://github.com/jincod/dotnetcore-buildpack/commit/64cf9ce03492e74b1e69483004e7f62d007a1872

 I would like to however set this environment variable myself. I have set a config var `ASPNETCORE_URLS` to `https://+:443` but this seems to be ignored.

The primary purpose of this is that I would like to have HTTPS running on my web application. Currently, I have HTTPS redirection working but since the application itself is not listening on HTTPS due to the above line, this won't work. 

An alternative solution is also welcome. I am not sure if I can somehow override what is happening in `profile/aspnetcore-defaults.sh` to my preference? 

Thanks

**Comment by jincod** [comment]
Hi @kiran94,

Do you want to use your custom certificate or something else?

Currently it's not possible to set custom port instead of `$PORT` provided by Heroku. More info here https://devcenter.heroku.com/articles/runtime-principles#web-servers

**Comment by kiran94** [comment]
Hi @jincod 

Right but I would like to have my application running **just** on `https` and it looks like `aspnetcore-defaults.sh` forces me into `http`?

I want to do 
```sh
export ASPNETCORE_URLS="https://+:$PORT"
```

Let me know if I am missing something or anything is unclear. 
Thanks

**Comment by jincod** [comment]
> All default appname.herokuapp.com domains are already SSL-enabled and can be accessed by using https, for example, https://appname.herokuapp.com.

https://devcenter.heroku.com/articles/ssl-endpoint

In this case Heroku terminate https traffic and routes http to asp.net app. You need to implement redirect http->https for asp.net app. I described this approach here https://jincod.github.io/2018/11/17/ensure-https-for-aspnetcore-on-heroku/

**Comment by kiran94** [comment]
Thanks for the article, I followed this and the redirection works but the ASP.NET Core application itself is not listening to `https`:

```sh
2019-04-08T17:13:44.159372Z app[web.1]: Hosting environment: Staging
2019-04-08T17:13:44.159413Z app[web.1]: Content root path: /app/heroku_output
2019-04-08T17:13:44.15956Z app[web.1]: Now listening on: http://[::]:28306
```

So even when redirection happens, the application is not listening under that scheme. 

Thanks,
Kiran

**Comment by jincod** [comment]
Correct, Heroku router terminate https connection and routes http traffic to app. It is general schema.
