### ISSUE TITLE
Error R10 (Boot timeout)

### ISSUE THREAD

**Issue by Axelics** [jincod/dotnetcore-buildpack#84]
My app compiles, but the console shows "Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch" after a while. I know it's related to my app binding the wrong port, since heroku provides its own port, but I don't know how to fix it.

**Comment by jincod** [comment]
Hi @Axelics,

Could you please share your `appsettings.json` and `Program.cs`? Also make sure that you don't commit `launchSettings.json`.

**Comment by Axelics** [comment]
Hi, this is my Program.cs [https://pastebin.com/ihHGTF5z](url)
And this is appsettings.json [https://pastebin.com/xqNRiJqk](appsettings.json)

**Comment by jincod** [comment]
I think the problem with discord client. Is it works with Discord client initialisation?

**Comment by Axelics** [comment]
Nope, it's not a Discord problem. Discord client works perfectly, logs say that everything works, and the bot becomes online and responds to subscribed events until it crashes

**Comment by jincod** [comment]
Could you share logs?

**Comment by Axelics** [comment]
This is what heroku [outputs](https://pastebin.com/fNhfikNt)

**Comment by jincod** [comment]
Does it work with commented out `new Program().StartAsync().GetAwaiter().GetResult();`?

**Comment by Axelics** [comment]
It appears that it works, but the app itself doesn't - it doesn't output any Console.Writelines i put, and the bot stays offline. Here's what [console](https://pastebin.com/vXeTPgXm) looks like

**Comment by jincod** [comment]
I suppose problems here: 

`await Task.Delay(-1);`

```csharp
new Program().StartAsync().GetAwaiter().GetResult();
// This part doesn’t execute because infinity delay
Console.WriteLine(“Started”);
CreateWebHostBuilder(args).Build().Run();
```

I suggest to use webhook approach to communicate with Discord

**Comment by Axelics** [comment]
Thank you kindly, after removing delay it works perfectly.
