### ISSUE TITLE
Deployment fails due to missing reference assemblies for .NetFramework 4.0

### ISSUE THREAD

**Issue by spencerparkin** [jincod/dotnetcore-buildpack#87]
Hi, I get the following error on deployment...

```
/app/tmp/cache/dotnet/2.2.301/sdk/sdk/2.2.301/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/tmp/build_bcba700179aba2dbf110a1154b1427f7/GeometricAlgebra.csproj]
```

This might be a problem, not with the build-pack, but with the version of windows Heroku is using to deploy on.  I'm going to try removing my dependency on .NetFramework v4.0 to see if that helps, but in the mean time, I'm wondering if there is anything I may be doing wrong.

My crappy ASP.NET application can be found [here](https://github.com/spencerparkin/GeometricAlgebra).

Thanks for any time you spend looking at this.

**Comment by jincod** [comment]
This buildpack supports only .NET Core applications

> https://github.com/spencerparkin/GeometricAlgebra

It's not a .NET Core app. Try to start from this article https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.2

**Comment by spencerparkin** [comment]
Oh okay.  Thanks for clearing things up for me.  Admittedly, I had no idea there was some sort of distinction between .Net dependencies (e.g., .Net Core vs. .Net Framework.)  For all I know my app is also using .Net Pooper-scoopers.  Wouldn't be surprised to find that out.

**Comment by spencerparkin** [comment]
Just for the record, I ran the compatibility analyzer extension for VS, and it gave the following result...

![image](https://user-images.githubusercontent.com/1977523/62438970-1961ba80-b707-11e9-85f3-20abecacce97.png)

This was, of course, after I threw out whatever I thought was incompatible with asp.net core.

Despite this, the deployment is still trying to reference some .net framework assemblies.  I'm still looking into the problem.
