### ISSUE TITLE
ClearDB Connection String

### ISSUE THREAD

**Issue by Mascasc** [jincod/dotnetcore-buildpack#89]
Is there a standard connection string to use with the ClearDB add-on?

I'm trying to configure my project to use this provider and I'm not sure what to use as my connectionString with EF Core.

Any help would be appreciated.

**Comment by jincod** [comment]
Hi @mascasc 

Check this issue https://github.com/jincod/dotnetcore-buildpack/issues/33#issuecomment-381421539

**Comment by Mascasc** [comment]
I believe this will help my issue.
Thank you for this.
