### ISSUE TITLE
Build failing with SDK version not found

### ISSUE THREAD

**Issue by mbrewerton** [jincod/dotnetcore-buildpack#90]
I've been making some front-end changes to my Angular 7 / .Net Core app over the last few weeks, and I'm now getting build failures on Heroku from the Buildpack.

I've not made **any** changes to the .net Core side, my changes are purely on the Angular side. However when I now try and push to my Heroku remote I'm getting a failure:

```
remote: -----> ASP.NET Core app detected        
remote: Installing dotnet        
remote: -----> Removing old cached .NET version        
remote: -----> Fetching .NET SDK        
remote: -----> Fetching .NET Runtime        
remote: publish MyApp/MyApp.csproj for Release        
remote: A compatible SDK version for global.json version: [2.2.203] from [/tmp/build_b72582edd2f4c450895a10a048bfdb3b/global.json] was not found  
```

**Comment by mbrewerton** [comment]
It looks like after looking through the code changes on the buildpack, I saw that there's change in SDK version in the commit [#776fc72](https://github.com/jincod/dotnetcore-buildpack/commit/776fc72e0b2290950929b5a9b4c941b29819eb4f) to 2.2.301. Not sure why this was working when I was running 2.2.203 (which was different to 2.2.204 before that commit), but it seems to be okay now.

Is there a better way to handle the SDK versions?

**Comment by jincod** [comment]
Hi @mbrewerton,

> However when I now try and push to my Heroku remote I'm getting a failure:
You use `global.json`. This buildpack ignores `global.json` and you get latest version.

> Not sure why this was working when I was running 2.2.203 (which was different to 2.2.204 before that commit)

It's a cache.

I've pushed some tags. Now you can use url `https://github.com/jincod/dotnetcore-buildpack#v2.2.203`

More info https://devcenter.heroku.com/articles/buildpacks#buildpack-references

**Comment by mbrewerton** [comment]
Hi @jincod Thank you for your reply - And apologies for not responding to you.

I ran into this issue again today due to the newest build you've released - and when heading to the buildpack page I saw the `#version` section and it's working like a charm now.

Thanks for your help, and thanks for creating the buildpack and keeping it updated.
