### ISSUE TITLE
Procfile question. 

### ISSUE THREAD

**Issue by mmodsgtav** [jincod/dotnetcore-buildpack#93]
Hi, I used your buildpack and everything is working right, but when my application is deployed for a minute, it gives a port error. How I should set my Procfile to fix this error? Thank!

**Comment by jincod** [comment]
Hi @mmodsgtav

Could you please attach the heroku logs? Have you overridden Procfile?

**Comment by mmodsgtav** [comment]
First of all thanks for the quick answer. My heroku log says:
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch this error.

And my Procfile looks like this:
Web: C# Program.cs rails server -p $PORT

**Comment by jincod** [comment]
It looks strange. Is it asp.net core app?

**Comment by mmodsgtav** [comment]
Visual C# .NET Core application

**Comment by jincod** [comment]
Have you checked this example https://github.com/jincod/AspNetCoreDemoApp?
