### ISSUE TITLE
How Does The Port / Proxy Work In The Sample App

### ISSUE THREAD

**Issue by raytiley** [jincod/dotnetcore-buildpack#96]
Hello. Thanks for providing this build pack, I've been messing around with it a bit and it seems great.

I'm trying to combine it in a multi buildpack solution with the static build pack and a proxy to localhost so that an SPA can be served out from the static and the api could be handled by this build pack. 

However I don't see how to control the port that the dotnet app listens on. I see in the sample app you setup a proxy to port 5000, but how do you control that this is the port the dotnet app is running on?

Right now I just get a bad gateway from the proxy.

Thanks for any insight how your example app works.

**Comment by jincod** [comment]
Hi @raytiley,

Have you already checked https://github.com/jincod/AspNetCoreDemoApp?

Here I use next approach:
- use node.js buildpack to build SPA
- use this buildpack to build and run .net app

Required parts:
- https://github.com/jincod/AspNetCoreDemoApp/blob/master/src/AspNetCoreDemoApp/AspNetCoreDemoApp.csproj#L11 builds SPA to `build` folder and copy files to `wwwroot`

- https://github.com/jincod/AspNetCoreDemoApp/blob/master/src/AspNetCoreDemoApp/Startup.cs#L29 this option allows to serve static by ASP.NET Core app.

- https://github.com/jincod/AspNetCoreDemoApp/blob/master/src/AspNetCoreDemoApp/Startup.cs#L39-L42 and web.config allow to serve `index.html` for all requests except `/api/` calls.

About port controlling https://devcenter.heroku.com/articles/runtime-principles#web-servers

Heroku set `PORT` environment variable and buildpack use it here https://github.com/jincod/dotnetcore-buildpack/blob/master/profile/aspnetcore-defaults.sh
