### ISSUE TITLE
Entity Framework migration in dotnet 3.0

### ISSUE THREAD

**Issue by matthewfarrell** [jincod/dotnetcore-buildpack#99]
It appears that the command to migrate the database has changed for dotnet 3.0, you now need install the entity framework migration tool separately. I have had to use the below in the .csproject file to get the migrations to run. This does not seem like the most ideal solution, is there a better way to do it?

```xml
  <Target Name="PrePublishTarget" AfterTargets="Publish">
    <Exec Command="dotnet new tool-manifest" />
    <Exec Command="dotnet tool install dotnet-ef --version 3.0.0" />
    <Exec Command="dotnet tool run dotnet-ef database update" />
  </Target>
```

**Comment by jincod** [comment]
Hi @matthewfarrell,

You can try this solution https://github.com/jincod/dotnetcore-buildpack/issues/46#issuecomment-397832490 (I use the same).

Also I need to verify `dotnet tools` approach and update README.md (https://github.com/jincod/dotnetcore-buildpack/pull/47)

**Comment by jincod** [comment]
Hi @matthewfarrell 

We've added support for `dotnet local tools`. You can check it here #103 and #104

**Comment by sixpeteunder** [comment]
Hi @jincod, I suggest you make a note of the need for dotnet-tools.json in the README. This file is important to deployment and yet it is only mentioned here.

**Comment by jincod** [comment]
Hi @sixpeteunder 

Feel free to send a PR
